### ISSUE TITLE
P1: Add 3rd meter positions

### ISSUE THREAD

**Issue by Rrrr4321** [jtebbens/com.homewizard#100]
As per:
https://community.homey.app/t/app-pro-homewizard/19267/1508?u=rrrr

{
“wifi_ssid”: “not that one”,
“wifi_strength”: 62,
“smr_version”: 50,
“meter_model”: “Kaifa AIFA-METER”,
“unique_id”: “K50322”,
“total_power_import_kwh”: 17188.517,
“total_power_import_t1_kwh”: 4520.691,
“total_power_import_t2_kwh”: 174.637,
“total_power_import_t3_kwh”: 12493.189,
“total_power_export_kwh”: 21057.65,
“total_power_export_t1_kwh”: 375.473,
“total_power_export_t2_kwh”: 0,
“total_power_export_t3_kwh”: 20682.183,
“active_power_w”: -12400,
“active_power_l1_w”: -4530,
“active_power_l2_w”: -4310,
“active_power_l3_w”: -3540,
“active_voltage_l1_v”: 226,
“active_voltage_l2_v”: 231,
“active_voltage_l3_v”: 230,
“active_current_a”: 54.1,
“active_current_l1_a”: 20,
“active_current_l2_a”: 18.7,
“active_current_l3_a”: 15.4,
“external”: 
}

**Comment by jtebbens** [comment]
Test version 3.3.15 released:

https://homey.app/a/com.homewizard/test/

**Comment by Rrrr4321** [comment]
Thank you!

I reinstalled p1 but the device shows two additional fields but they are
empty and their  name is - (see screenshot).

Do you want me to wait and see if they fill up?

**Comment by jtebbens** [comment]
There should eventually be data. Try to close the Homey app on your phone/tablet. If not, sent me a diagnostic report.
The lines added in code are straightforward so can't see if there is an error, moreover I dont have a T3 so cant see/test myself.

**Comment by Rrrr4321** [comment]
I restarted my mobile app and HW app a couple of times. Reinstalled the
device again.

Initially it has empty fields, next time they have disappeared.

Do you want access to my Homey?

**Comment by jtebbens** [comment]
I need the logs, sent me diagnostics



-----Original message-----

**Comment by Rrrr4321** [comment]
30db4ace-dc27-4974-a324-47507f1d42f6

**Comment by jtebbens** [comment]
Ok problem found, try 3.3.16.



-----Original message-----

**Comment by Rrrr4321** [comment]
All seems excellent!
Note: again I see a difference between immediately opening the device and a
few moments later. But it does not bother me.

Many thanks!

**Comment by jtebbens** [comment]
Good, what do you mean with immediately opening device and a few moments later?

There is a delay on updates in Homey and polled every 10s.



-----Original message-----

**Comment by Rrrr4321** [comment]
After reinstalling I opened the device and saw the extra field at the
bottom of the screen. See screenshot in my previous email

After closing the device and reopening the field are gone.

**Comment by jtebbens** [comment]
That should only be once after (re)install. It checks if you have certain datapoints in P1 or not. When it doesnt it removes them so that is the blip. This should not be the case later.

Groet,
Jeroen

Op 23 aug 2024 om 13:20 heeft Rrrr4321 ***@***.***> het volgende geschreven:

﻿


After reinstalling I opened the device and saw the extra field at the
bottom of the screen. See screenshot in my previous email

After closing the device and reopening the field are gone.

**Comment by Rrrr4321** [comment]
Cool that’s fine
Bedankt!

**Comment by jtebbens** [comment]
Alright let me push this version to stable.



-----Original message-----

**Comment by jtebbens** [comment]
Fixed in 3.3.16 pushed to stable/public
