### ISSUE TITLE
Energylink verbruik afgesneden op 0

### ISSUE THREAD

**Issue by modelist1** [jtebbens/com.homewizard#16]
Helaas wordt het verbruik afgesneden op nul terwijl het ech

**Comment by jtebbens** [comment]
Hoi, kan je even iets meer informatie geven want ik begrijp niet wat je bedoelt met afgesneden op 0.
Ik heb zelf ook Energylink en ervaar geen problemen.
Welke versie firmware van Homey heb je en welke versie van de Homewizard applicatie draai je nu?

**Comment by modelist1** [comment]
Hoi,

Ik draai op homewizard app 0.2.4 en Homey 2.5.2.  Het huidig vermogen staat op nul zie afbeelding terwijl er energie opgewekt wordt (-360) zie afbeelding homewizard. Ik zou graag de lader van mijn auto laten werken als de productie lager dan bijvoorbeeld -3600 staat.

Bedankt voor deze snelle reactie.

Ferdie
[image2.png]
[image1.png]
Op 18 sep. 2019 om 16:44 heeft jtebbens <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hoi, kan je even iets meer informatie geven want ik begrijp niet wat je bedoelt met afgesneden op 0.
Ik heb zelf ook Energylink en ervaar geen problemen.
Welke versie firmware van Homey heb je en welke versie van de Homewizard applicatie draai je nu?

**Comment by jtebbens** [comment]
Plaatjes werken niet hier via github. Maar volgens mij hebben we tot op heden alleen de gebruik en oplever waarde opgenomen in de code en niet de aggregate (netto waarde die negatief kan worden inderdaad). Heb je al gekeken naar better logic eventueel? Deze app kan je elke berekening doen dus ook gebruik - teruglevering.

Ik zal je verzoek opnemen als enhancement voor mocht ik weer tijd hebben aangezien het wat extra werk is om nog 1 variable op te nemen in de code (meerdere bestanden die aangepast moet worden).

Mvg,
Jeroen

**Comment by modelist1** [comment]
Helaas gaat dat met Logic niet werken. Ik heb geen meter tussen zonnepanelen en energylink. Dus weet niet wat de productie is. In de energylink staat huidig vermogen en dit is wat er netto gebruikt wordt =netto gebruik in HomeWizard. Is er meer opgewekt dan verbruikt dan staat in de homewizard -xxx maar in de energylink op de honey staat dan 0 bij huidig verbruik.

**Comment by jtebbens** [comment]
Ok jammer. Dan moet die netto variabele er nog een keer bij gemaakt worden. Geen idee wanneer maar zal pas eind okt worden als terug ben van vakantie en zakenreis.

**Comment by jtebbens** [comment]
Ik heb een nieuwe beta versie geupload naar Athom ter beoordeling. In deze beta versie 0.2.6 zit de uitbreiding van de Netto Huidig vermogen. Je zal waarschijnlijk je Energylink opnieuw moeten toevoegen. Je kan ook nogmaals je Energylink toevoegen (dubbel) en dan krijg je de nieuwe variabele erbij.

**Comment by modelist1** [comment]
Bedankt, werkt perfect. Ga nu proberen mijn tesla lader te sturen.

Ferdie

Op 14 okt. 2019 om 16:21 heeft jtebbens <notifications@github.com> het volgende geschreven:

﻿

Ik heb een nieuwe beta versie geupload naar Athom ter beoordeling. In deze beta versie 0.2.6 zit de uitbreiding van de Netto Huidig vermogen. Je zal waarschijnlijk je Energylink opnieuw moeten toevoegen. Je kan ook nogmaals je Energylink toevoegen (dubbel) en dan krijg je de nieuwe variabele erbij.

**Comment by jtebbens** [comment]
Prima dan zal ik hem daarna als stable vrijgeven.

**Comment by jtebbens** [comment]
Issue closed/solved
