### ISSUE TITLE
Homey Energy

### ISSUE THREAD

**Issue by larsnet** [jtebbens/com.homewizard#20]
Komt er in de Homewizard app ook ondersteuning voor Homey Energy?

**Comment by jtebbens** [comment]
Ja, dat is wel de bedoeling. Homey firmware is nog experimental dus nog even afwachten totdat deze final is. Daarna zal ik proberen de Energylink geschikt te maken voor Homey Energy.

**Comment by larsnet** [comment]
Bedankt! We wachten het rustig af.

**Comment by jtebbens** [comment]
Beta channel heeft Energy support

**Comment by larsnet** [comment]
Thanks for the update.
