### ISSUE TITLE
Kan homewizard niet selecteren

### ISSUE THREAD

**Issue by MartinvD1** [jtebbens/com.homewizard#21]
Goedemiddag, Ik heb de app van HomeWizard op de Homey geinstalleerd. Ik kan de Heatlink, Energylink enz. niet installeren op de Homey omdat ik de Homewizard niet kan selecteren. Wat doe ik fout?

**Comment by jtebbens** [comment]
Hallo,

Je moet eerst de HomeWizard toevoegen als device pas dan kan je andere units als Energylink en Heatlink toevoegen.

Verstuurd vanaf mijn iPhone

Op 27 okt. 2019 om 17:09 heeft MartinvD1 <notifications@github.com> het volgende geschreven:

﻿

Goedemiddag, Ik heb de app van HomeWizard op de Homey geinstalleerd. Ik kan de Heatlink, Energylink enz. niet installeren op de Homey omdat ik de Homewizard niet kan selecteren. Wat doe ik fout?

**Comment by MartinvD1** [comment]
Klopt, heb ik gedaan. Ik heb het nu op een ander apparaat dezelfde stappen
gedaan en ondervond ik geen problemen. Het lijkt dus dat het gebruikte
apparatuur invloed op de installatie heeft.

Op zo 27 okt. 2019 17:28 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
Vreemd, wellicht toch iets fout gegaan met toevoegen op de eerste. Al geprobeerd te verwijderen en opnieuw toevoegen?

Verstuurd vanaf mijn iPhone

Op 27 okt. 2019 om 19:03 heeft MartinvD1 <notifications@github.com> het volgende geschreven:

﻿Klopt, heb ik gedaan. Ik heb het nu op een ander apparaat dezelfde stappen
gedaan en ondervond ik geen problemen. Het lijkt dus dat het gebruikte
apparatuur invloed op de installatie heeft.

Op zo 27 okt. 2019 17:28 schreef jtebbens <notifications@github.com>:

**Comment by MartinvD1** [comment]
Ja, een paar keer totdat ik het via mijn telefoon probeerde. Op mijn
telefoon lukte het in één keer. De eerst paar keer was op een android
tablet.

Op zo 27 okt. 2019 19:23 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
Ok toch vreemd zoals ik eerder schreef. Maar goed, ik begrijp dat nu gelukt is.

Kind regards / Groet,
Jeroen

Op 27 okt. 2019 om 19:28 heeft MartinvD1 <notifications@github.com> het volgende geschreven:

﻿Ja, een paar keer totdat ik het via mijn telefoon probeerde. Op mijn
telefoon lukte het in één keer. De eerst paar keer was op een android
tablet.

Op zo 27 okt. 2019 19:23 schreef jtebbens <notifications@github.com>:

**Comment by MartinvD1** [comment]
Niet helemaal gelukt. Als ik de heatlink wil instellen geeft hij een
foutmelding. Dat er iets is fout gegaan bij het verzenden van de waarde.
Waar ligt dat aan?

Op zo 27 okt. 2019 19:30 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
Dat ligt aan hoe vaak (te snel) je waarde van Heatlink aanpast. Dus de draai schijf voor temperatuur instellen.

Verstuurd vanaf mijn iPhone

Op 28 okt. 2019 om 17:25 heeft MartinvD1 <notifications@github.com> het volgende geschreven:

﻿Niet helemaal gelukt. Als ik de heatlink wil instellen geeft hij een
foutmelding. Dat er iets is fout gegaan bij het verzenden van de waarde.
Waar ligt dat aan?

Op zo 27 okt. 2019 19:30 schreef jtebbens <notifications@github.com>:

**Comment by MartinvD1** [comment]
Nee, hij geeft de foutmelding gelijk. (Bij 1x instellen). Ook getest in een
flow. Hij past de waarde tijdens een flow ook niet aan.

Op ma 28 okt. 2019 17:37 schreef jtebbens <notifications@github.com>:

**Comment by MartinvD1** [comment]
Helaas heeft dat ook niet gewerkt. Waar kan het nog meer aan liggen?

Op ma 28 okt. 2019 17:50 schreef jtebbens <notifications@github.com>:

**Comment by MartinvD1** [comment]
Foutmelding is nu wel wat specifieker. In plaats van een onbekende fout
geeft hij een time out fout van 30000ms.

Op ma 28 okt. 2019 19:49 schreef Martin van Dalen <dalenmartinvan@gmail.com

**Comment by MartinvD1** [comment]
Lijkt nu te werken, ik heb nogmaals de heatlink verwijderd en na het
verwijderen en opnieuw installeren de homey herstart.

Op ma 28 okt. 2019 20:03 schreef Martin van Dalen <dalenmartinvan@gmail.com

**Comment by jtebbens** [comment]
Ok. Ik ga de code er nog eens op nalopen. Dit klinkt als een compleet nieuw probleem met de laatste Homey firmware. M

Verstuurd vanaf mijn iPhone

Op 28 okt. 2019 om 20:13 heeft MartinvD1 <notifications@github.com> het volgende geschreven:

﻿Lijkt nu te werken, ik heb nogmaals de heatlink verwijderd en na het
verwijderen en opnieuw installeren de homey herstart.

Op ma 28 okt. 2019 20:03 schreef Martin van Dalen <dalenmartinvan@gmail.com

**Comment by MartinvD1** [comment]
Goede avond,

Ik zag dat je de HomeWizard app had geüpdatet. Maar de verbinding tussen
Homey en HomeWizard lijkt niet stabiel. De ene keer kan ik de heatlink
zonder problemen aanpassen de andere keer niet. Ook komen de preset
veranderingen niet goed door op de Homey. Ben je al bekend met dit
probleem?

Op ma 28 okt. 2019 20:16 schreef jtebbens <notifications@github.com>:
