### ISSUE TITLE
Homey 3.0 Support ; Energylink won't appear

### ISSUE THREAD

**Issue by AlfredG92** [jtebbens/com.homewizard#22]
Found the following description on V0.2.7:
QTE
Adding Homey 3.0 support (Watcher & Energylink) NOTE: YOU NEED TO PAIR YOUR ENERGYLINK AGAIN TO MAKE THIS WORK!
UQTE

Did remove the Energylink from Homey. Then rebooted the Homewizard app in Homey. Afterwards added the Energylink again. But unfortunatly I don't get any Energy icon on the ribbon of the Homey app. Is there anything which I did wrong?

**Comment by jtebbens** [comment]
You might need to logout and login the Homey app to have Energy tab updated.

Op 11 nov. 2019 om 10:24 heeft AlfredG92 <notifications@github.com> het volgende geschreven:

﻿

Found the following description on V0.2.7:
QTE
Adding Homey 3.0 support (Watcher & Energylink) NOTE: YOU NEED TO PAIR YOUR ENERGYLINK AGAIN TO MAKE THIS WORK!
UQTE

Did remove the Energylink from Homey. Then rebooted the Homewizard app in Homey. Afterwards added the Energylink again. But unfortunatly I don't get any Energy icon on the ribbon of the Homey app. Is there anything which I did wrong?

**Comment by AlfredG92** [comment]
Hi jtebbens,

Thanks for above. Just logout and logged in again and Energy tab and Energylink is available.
Thanks for helping me out.

**Comment by jtebbens** [comment]
Good to hear!
Make sure you run version 0.2.8 of the app so it will register properly with potential solar panels 



Op 11 nov. 2019 om 11:21 heeft AlfredG92 <notifications@github.com> het volgende geschreven:

﻿

Hi jtebbens,

Thanks for above. Just logout and logged in again and Energy tab and Energylink is available.
Thanks for helping me out.

**Comment by AlfredG92** [comment]
Automatically updating as i suppose you guys don't do update for no reason ;-)
