### ISSUE TITLE
Homewizard

### ISSUE THREAD

**Issue by tomlangbroek** [jtebbens/com.homewizard#23]
> HomeWizard error: apparaat niet bedienbaar
Geïnstalleerd ip adres ingevuld + poortnummer / paswoord, dit gaat goed maar als de app open krijg ik de boodschap ‘apparaat niet bedienbaar’

**Comment by jtebbens** [comment]
Klopt, je moet nu daarna de losse onderdelen apart toevoegen.

**Comment by tomlangbroek** [comment]
Jeroen, 
Energy link doet het prima maar Homewizard basis station doet het niet dan krijg ik dit apparaat is niet te bedienen. 
M.vr.gr. Tom

Verstuurd vanaf mijn iPhone

**Comment by jtebbens** [comment]
Zoals eerder gemeld moet je de thermometers, windmeter, regenmeter etc apart toevoegen. Homewizard heeft geen elementen die je direct benaderd. We gebruiken dit alleen om de zaken te koppelen via de Homewizard.

**Comment by amarkest** [comment]
Jeroen, duidelijk. Maar wellicht word veel mensen een hoop zoekwerk bespaard als het gebruik vd Homewizard app bij de FAQ,s op de site van Homey staat. Ik heb ook veel zoekwerk en een paar mails nodig gehad om bij jouw simpele uitleg te komen.

**Comment by jtebbens** [comment]
Documentatie bijgewerkt (Readme)
