### ISSUE TITLE
Homewizard not working with Homey firmware 5.0.0 (experimental release)

### ISSUE THREAD

**Issue by jtebbens** [jtebbens/com.homewizard#26]
![sdkhomewizard](https://user-images.githubusercontent.com/38841639/88838256-8fddaf00-d1d9-11ea-8838-1c831cc207de.jpg)
ik krijg deze melding als ik homwizard aan zet

_Originally posted by @plompen in https://github.com/jtebbens/com.homewizard/issues/24#issuecomment-665827148_

**Comment by jtebbens** [comment]
This is a known issue. Homewizard app is still a sdkv1 version which will not work in Homey 5.0.0. Which is still experimental release. This new firmware will remove sdkv1 support and thus not work.

**Comment by plompen** [comment]
i hope someone can make this it worked so nicely

**Comment by plompen** [comment]
jtebbens can you make this

**Comment by plompen** [comment]
please

**Comment by jtebbens** [comment]
It’s holiday season so priorities are with family. I do know one developer started working on it but it is a lot of work changing the code from sdkv1 to v2.

**Comment by ricardovanlaarhoven** [comment]
I'm new to homey development but i'm trying to create a new light version of homewizard.
For now i'm only going to support the devices that you can't connect directly to homey (heatlink and energylink)
I'm hoping to release a first version this weekend.

**Comment by plompen** [comment]
ricard

beautiful i have both devices.

I hope you will succeed.

**Comment by jtebbens** [comment]
Development work underway, beta/test version can be found in the Homey app store.

Version 0.3.0 (beta) - SDKv2 
Homewizard (tested, working)
Energylink (tested, working)
Thermometers (tested, working)
Heatlink (not working, pending code change)
Windmeter (not working, pending code change)
Rainmeter (not working, pending code change)
Wattcher (not working, pending code change)

**Comment by jtebbens** [comment]
Issue should be resolved. Homewizard app is SDKv2 now and thus compatible with Homey 5.0.0
