### ISSUE TITLE
Homey app gestopt met werken

### ISSUE THREAD

**Issue by MartinvD1** [jtebbens/com.homewizard#36]
Goedemorgen, de homewizard app is gestopt met werken. Alle Homewizard onderdelen verwijderd uit Homey. Ik probeer nu homewizard weer opnieuw te installeren. Dat lukt niet. In homey krijg ik steeds de melding dat de app gestopt is. Heb jij nog tips?

**Comment by jtebbens** [comment]
Kan het zijn dat homewizard een ander ip adres heeft gekregen?
Nog een optie is app verwijderen en Homey herstarten (heeeeel soms blijft Homey hangen in het installeren of verwijderen van apps (maakt niet uit wat). Waardoor er een blauwe ring blijft draaien. Ik heb dit eerder gehad. Na een herstart kon ik Homewizard app opnieuw installeren en toen ging het goed.

**Comment by MartinvD1** [comment]
Bedankt.

IP adres is een vast adres. Dus daar kan het niet aan liggen.
Vanmorgen lukte het mij weer wel om de HomeWizard toe te voegen. Waar het aan lag weet ik niet. Ik heb wel een thermometer uit de HomeWizard verwijdert die opeens allemaal rare tekens had. Deze Thermometer weer opnieuw toegevoegd. Misschien dat het daar aan gelegen heeft.
Volgende keer zal ik eerst Homey herstarten na installeren/verwijderen apps.

**Comment by jtebbens** [comment]
Rare tekens in thermometer duidt op wifi communicatie problemen tussen Homey en Homewizard. Het is bijzonder lastig om steeds te controleren dat de JSON output correct is.
