### ISSUE TITLE
Homewizard devices NOT working in flows anymore.

### ISSUE THREAD

**Issue by hlvdzande** [jtebbens/com.homewizard#38]
All flows containing Homewizard devices e.g. thermometers, do not work anymore. A flow error (red triangle exclamation mark) appears in the card.
Worked fine for year.

Noticed this during migration from Homey to Homey Pro. In the old environment thr same problems.

Next to this I lost my Heatmiser app, it's gone from the app store.

What is happening? Athom wants to get rid of their most loyal customers???

**Comment by jtebbens** [comment]
Sorry I am not Athom. Not sure why you have red triangles. But sounds like a migration is the cause of the problem not the Homewizard app. Are you on Homey 4.2? Did you use the backup/recovery from Athom or what?

**Comment by hlvdzande** [comment]
Ik snap het even niet. Ik antwoord direct op jouw mail en vragen, er volgt
geen reactie en nu alleen Closed #38??

Groeten, Henk.

_______________________________________________________________________________
Re: [jtebbens/com.homewizard] Homewizard devices NOT working in flows
anymore. (#38)
Henk van der Zande <hlvdzande@gmail.com>
vr 5 feb. 17:44 (11 dagen geleden)
aan jtebbens/com.homewizard
Hello Jeroen,

Long time no see☺
Yes I'm running Homey 4.2.0 on a Homey Pro.
I tried to use the backup/recovery tool, but (guess what) it did not work.
I tried a dozen times, but I never got to the point that I could select my
backup to restore :-(
I installed everything new on the Pro, Apps, Devices, flow, etc.

Just like the heatmiser app (that just disappeared out of the Homey app
store), I think the latest version of Homewizard is very different from the
old one.

My old Homey is still working and there all my Homewizard based flows (13)
do not work anymore also.
On the Homey Pro I installed your (v1.1.8) Homewizard app.
Now I can't build flows with the Homewizard thermometers anymore, they all
fail in the same way.

Just to avoid potential conflicts between the Homeys, I turned my old homey
off.

Best regards,

Henk.

Op di 16 feb. 2021 om 10:00 schreef jtebbens <notifications@github.com>:

**Comment by jtebbens** [comment]
Hallo Henk. Ik kijk op Github en krijg alleen maar opmerkingen alsof ik van Athom ben en dat ben ik niet.
Laatste bericht die ik zie "All flows containing Homewizard devices e.g. thermometers, do not work anymore. A flow error (red triangle exclamation mark) appears in the card.
Worked fine for year.

Noticed this during migration from Homey to Homey Pro. In the old environment thr same problems.

Next to this I lost my Heatmiser app, it's gone from the app store.

What is happening? Athom wants to get rid of their most loyal customers???"

Dus ik kan hier niets mee. Maar nu krijg ik via de email een bericht die niet bij github staat dus ik begreep het even niet sorry.
Ik doe mijn best en weet niet waarom je Homewizard app een uitroep teken heeft.

Er is inmiddels een versie 2.0.0 uitgebracht (2.0.2) in test kijk even of dat wel beter gaat. Maar val mij AUB niet af op Athom want ik ben ook maar een gewone gebruiker die in zijn vrije tijd/hobby deze app gemaakt heeft.

**Comment by hlvdzande** [comment]
Bedankt Jeroen,

Ik had de github #38 niet begrepen en had alleen op je mail gereplied :-(
Vannacht spontaan Homewizard versie 2.0.1 gekregen.

Verder speurwerk levert op dat het probleem bij het ophalen van de Homewizard temperatuur via Logica niet beperkt blijft tot Homewizard devices, lijkt bij meerder andere devices ook niet te werken.

Sorry, misschien iets te heftig gereageerd. Na het debacle met het restoren naar de nieuwe Homey Pro en het verdwijnen van mijn Heatmiser app, bleken de flows met de homewizard temp ook niet te werken. Grrrh
Na de goede ervaringen in het verleden dacht ik begin bij Jeroen, daar krijg ik zinvolle antwoorden/suggesties van.

Ik weet niet of jij iets weet van veranderingen in de Logica app (ik selecteer kaart "Logica .... is kleiner dan ...", ik kies dan de homewizard temperatuur uit de lijst en kies voor bv 17). Ik weet niet wat ik fout doe.

Groeten, Henk.

**Comment by jtebbens** [comment]
Die bewuste mail heb ik dus nooit gekregen dus snapte er al niets van.
Ja klopt 2.0.1 en vandaag zelfs 2.0.2 naar stable dus die zal je ook krijgen.
Ik weet even niets van de Logica "app" dat is de ingebouwde Logica functionaliteit of bedoel je de Better Logic app?
Het kan zijn bij het wegvallen / uitroepteken van de de app dat je interne ID veranderd is en dan valt een Flow kaartje met bijv "als waarde veranderd" ook niet meer triggered (leeg kaartje dus als trigger). Deze zal je dan opnieuw moeten updaten met kaartje van wat je wenst. Dat staat los van de Homewizard app.

Ik heb helaas in het verleden veel vuldig dergelijke flows moeten herstellen. Soms helpt het om een dergelijke waarden naar een variabele eerste kopieren en dan die variabele te gebruiken in een actie. Ik heb bijvoorbeeld een lichtsterkte variabele die ik steeds update en dan de variabele gebruik als die veranderd. Dit is veiliger aangezien die interne variabele ALTIJD beschikbaar is en niet bijvoorbeeld wegvalt als een applicatie niet werkt of foutmelding geeft of dat ID flow kaartjes wegvallen of opeens een ander nummer krijgen. Ik werk al sinds 2016 met dezelfde Homey en vrees dat ik wellicht het zelfde probleem ga krijgen mocht ik OOIT een Homey Pro kopen.

**Comment by jtebbens** [comment]
Closing as there is nothing to do here (yet). If the issue comes again I will reopen it.
