### ISSUE TITLE
Koppeling Homewizard met Homey lukt niet

### ISSUE THREAD

**Issue by JelleYzn** [jtebbens/com.homewizard#40]
Hopelijk lukt de communicatie over mijn probleem via deze weg beter dan via de reviews. Ik heb alle posts die ik kon vinden over dit probleem gelezen en de adviezen opgevolgd. Ook iets geprobeerd met de geadviseerde optie: http://192.168.178.34//get-sensors waarbij het IP-adres dat van mijn Homewizard is (vast IP-adres). Nog even over het probleem: als ik de Homewizard wil toevoegen aan mijn apparaten moet ik het IP-adres van de Homewizard invullen en daarna het wachtwoord. Vervolgens klikken op 'Opslaan'. Er gebeurt dan niets: geen enkele melding en ook de LED-ring van de Homey blijft rustig doordraaien met de verschillende kleurtjes: geen rood of groen. Voor de goede orde meld ik nog dat ik mijn modem opnieuw heb geboot, de Homey idem dito, de Homewizard ook, de app verwijderd en opnieuw geïnstalleerd.

**Comment by jtebbens** [comment]
Dan is of je ip adres niet goed of je wachtwoord.
Als je in browser het bijvoorbeeld adres http://192.168.1.10/hiermoetjewachtwoordstaan/get-sensors

Tijdens koppelen gebeurt precies dit op de achtergrond.
Ik kan het helaas niet makkelijker maken dan dit.

Anders zal je met de hwconfig van homewizard website je homewizard moeten configeren met een nieuw wachtwoord of als je niet via internet router een vast ip adres kan een vast adres in de hwconfig tool configuren.

**Comment by JelleYzn** [comment]
Het wachtwoord heb ik geverifieerd door lokaal aan te loggen op de HW. En blijkens het netwerkoverzicht van mijn Fritzbox klopt het IP-adres ook. Geverifieerd door het IP adres in de browser in te tikken.
Maar misschien zie ik iets over het hoofd en zal de HW toch maar opnieuw configureren.

Bedankt in ieder geval voor je reactie en hulp tot zover.

Met vriendelijke groet 
Jelle Dijkstra 

Verstuurd vanaf mijn iPad

**Comment by jtebbens** [comment]
Zitten homey en homewizard op zelfde wifi netwerk?
Mogen wifi apparaten onderling met elkaar communiceren?
Heb je de brouwser nu geprobeerd dus niet de homewizard app op je mobiel of tablet?
En let op het wachtwoord is dus niet je Homewizard online account maar enkel en alleen een lokaal wachtwoord zonder email adres.

**Comment by JelleYzn** [comment]
Het is nu gelukt vanuit de Homey app. Precies hetzelfde gedaan als al die andere keren. Ik zag dat de HomeWizard app geupdate was naar versie 2 en dacht: ik probeer het nog eens. En jawel, ging gesmeerd.

Met vriendelijke groet
Jelle Dijkstra 

Verstuurd vanaf mijn iPad

**Comment by jtebbens** [comment]
Klopt afgelopen weekend mDNS ondersteuning toegevoegd. 
Fijn om horen dat het nu werkt.
