### ISSUE TITLE
Energie Link after update to version 1.1.18

### ISSUE THREAD

**Issue by Hilluk** [jtebbens/com.homewizard#42]
After the implementation of version 1.1.18 of the Homewizard app. Th information exchange between the Energylink and Homey  Homewizard app has been interrupted. So I don't get any new information in my Energy tab

**Comment by jtebbens** [comment]
Try version 2.0.2 which is the latest in the app store.

**Comment by Hilluk** [comment]
Hallo Jeroen,

 

At the moment I am already using version 2.0.2.

This has been automaticly downloaded and installed 5 days ago.

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:09
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

Try version 2.0.2 which is the latest in the app store.

**Comment by jtebbens** [comment]
Please verify if your homewizard still is reachable. The latest version has timeout checking added to avoid memory problems.
Take a browser and put:

http://<ip address homewizard/<password>/get-sensors

See if it shows data (this is the core functionality of the app). I recon the issue is about local wifi connectivity. So either the connection is very long. Maybe I have to finetune it more to cope with slow responses between Homey and Homewizard.
This hard for me to troubleshoot. After checking with a browser and see it works please click on "Diagnostic Report" option that comes with the app. This should trigger the logfile to me and "hopefully" show me the reason of your connectivity issue.

**Comment by Hilluk** [comment]
After putting te requested URL in my browser I got the following result :

 

{"status": "failed", "error": 1, "version": "3.403", "request": {"route": "/get-sensors" }}

 

The Code of the Diagnostic report is 982A1D

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:24
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

Please verify if your homewizard still is reachable. The latest version has timeout checking added to avoid memory problems.
Take a browser and put:

http:// <http://%3cip> <ip address homewizard//get-sensors

See if it shows data (this is the core functionality of the app). I recon the issue is about local wifi connectivity. So either the connection is very long. Maybe I have to finetune it more to cope with slow responses between Homey and Homewizard.
This hard for me to troubleshoot. After checking with a browser and see it works please click on "Diagnostic Report" option that comes with the app. This should trigger the logfile to me and "hopefully" show me the reason of your connectivity issue.

**Comment by jtebbens** [comment]
To me this error says your using the wrong password.

**Comment by Hilluk** [comment]
Where and in which format, should I put the password in the URL?

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:40
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

To me this error says your using the wrong password.

**Comment by jtebbens** [comment]
http://1.1.1.1/password/get-sensors

Kind regards / groet,
Jeroen

Op 22 feb. 2021 om 17:44 heeft Hilluk <notifications@github.com> het volgende geschreven:

﻿


Where and in which format, should I put the password in the URL?

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:40
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

To me this error says your using the wrong password.

**Comment by Hilluk** [comment]
Hallo Jeroen,

 

Now I have don it with the right password. This is the result.

 

{"status": "ok", "version": "3.403", "request": {"route": "/get-sensors" }, "response": {"preset":0,"time":"2021-02-23 12:02","switches":[{"id":40,"name":"Zonscherm","type":"somfy","mode":0,"favorite":"no"},{"id":41,"name":"Rolluik groot","type":"somfy","mode":0,"favorite":"no"},{"id":42,"name":"Rolluik klein","type":"somfy","mode":0,"favorite":"no"},{"id":43,"name":"Luifel voor","type":"somfy","mode":0,"favorite":"no"},{"id":44,"name":"Luifel zijkant","type":"somfy","mode":0,"favorite":"no"}],"uvmeters":[],"windmeters":[{"id":5,"name":"Wind","model":0,"unit":0,"ws":8.0,"dir":"NNW 337","gu":13.0,"wc":19.7,"te":19.7,"ws+":7.8,"ws+t":"10:40","ws-":4.6,"ws-t":"10:25","favorite":"no"}],"rainmeters":[{"id":6,"name":"Regenmeter","model":0,"mm":0.0,"3h":0.0,"favorite":"no"}],"thermometers":[{"id":0,"name":"Achtertuin","channel":1,"model":0,"te":16.9,"hu":70,"te+":16.9,"te+t":"11:51","te-":15.0,"te-t":"10:38","hu+":73,"hu+t":"10:25","hu-":70,"hu-t":"11:46","outside":"yes","favorite":"no"},{"id":1,"name":"Kantoor","channel":2,"model":0,"te":16.4,"hu":53,"te+":16.4,"te+t":"11:31","te-":15.8,"te-t":"10:25","hu+":54,"hu+t":"10:25","hu-":52,"hu-t":"10:40","outside":"no","favorite":"no"},{"id":2,"name":"Slaapkamer","channel":3,"model":0,"te":14.7,"hu":63,"te+":14.8,"te+t":"11:53","te-":13.2,"te-t":"10:34","hu+":76,"hu+t":"10:34","hu-":63,"hu-t":"10:25","outside":"no","favorite":"no"},{"id":3,"name":"Woonkamer","channel":4,"model":0,"te":19.6,"hu":56,"te+":19.6,"te+t":"12:01","te-":19.4,"te-t":"10:27","hu+":57,"hu+t":"10:26","hu-":56,"hu-t":"10:55","outside":"no","favorite":"no"},{"id":4,"name":"Luifel entree","channel":5,"model":0,"outside":"no","favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [{"id":0,"favorite":"no","name":"EnergyLink","code":"631743","t1":"solar","c1":800,"t2":"none","c2":0,"tariff":2,"s1":{"po":6446,"dayTotal":9.85,"po+":7377,"po+t":"11:47","po-":0,"po-t":"00:01"},"s2":null,"aggregate":{"po":-5890,"dayTotal":-2.12,"po+":2695,"po+t":"00:35","po-":-6787,"po-t":"11:47"},"used":{"po":556,"dayTotal":7.43,"po+":4115,"po+t":"11:45","po-":0,"po-t":"10:19"},"gas":{"lastHour":0.00,"dayTotal":0.20},"kwhindex":1.89,"wp":5200}], "heatlinks": [], "hues": [], "scenes": [], "kakusensors": [{"id":0,"name":"Voordeur bel","status":null,"type":"doorbell","favorite":"no","timestamp":"00:00","cameraid":null},{"id":1,"name":"Rook","status":null,"type":"smoke","favorite":"no","timestamp":"00:00","cameraid":null}], "cameras": []}}

 

When I look in the Homey I only get results of 12 days ago of my thermometers, the windmeter and the Energylink

 

Kind regards

 

Paul

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:47
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

http://1.1.1.1/password/get-sensors

Kind regards / groet,
Jeroen

Op 22 feb. 2021 om 17:44 heeft Hilluk <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

﻿


Where and in which format, should I put the password in the URL?



Van: jtebbens <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: maandag 22 februari 2021 17:40
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com <mailto:com.homewizard@noreply.github.com> >
CC: Hilluk <p.f.hilkhuysen@ziggo.nl <mailto:p.f.hilkhuysen@ziggo.nl> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)



To me this error says your using the wrong password.

**Comment by Hilluk** [comment]
Hallo Jeroen,

 

Ik heb de app verwijderd en de Homey opnieuw opgestart. Daarna de app opnieuw geïnstalleerd en nu lijkt het allemaal goed te werken.

 

Vriendelijke groet

 

Paul

 

Van: jtebbens <notifications@github.com> 
Verzonden: maandag 22 februari 2021 17:47
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com>
CC: Hilluk <p.f.hilkhuysen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)

 

http://1.1.1.1/password/get-sensors

Kind regards / groet,
Jeroen

Op 22 feb. 2021 om 17:44 heeft Hilluk <notifications@github.com <mailto:notifications@github.com> > het volgende geschreven:

﻿


Where and in which format, should I put the password in the URL?



Van: jtebbens <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: maandag 22 februari 2021 17:40
Aan: jtebbens/com.homewizard <com.homewizard@noreply.github.com <mailto:com.homewizard@noreply.github.com> >
CC: Hilluk <p.f.hilkhuysen@ziggo.nl <mailto:p.f.hilkhuysen@ziggo.nl> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Onderwerp: Re: [jtebbens/com.homewizard] Energie Link after update to version 1.1.18 (#42)



To me this error says your using the wrong password.
