### ISSUE TITLE
Save button does nothing when adding base station

### ISSUE THREAD

**Issue by Captain-Chaos** [jtebbens/com.homewizard#43]
I'm trying to pair my HomeWizard base station to my Homey, but when I press the `Opslaan` button after entering the correct IP address and password, nothing happens. It does not proceed, there is no error. It just sits there as if I never pressed the button.

The app version is 2.0.2 and Homey version is 5.0.2. I've verified that the base station is operational and reachable by going to http://ip-address/password/get-sensors in a browser from the same phone I'm trying to link the base station from and that works. The HomeWizard app on the same phone also works fine. I also tried doing the same from a tablet, with the same result.

**Comment by jtebbens** [comment]
Are you sure there is no accidental space before or after the ip address. Another thought comes to mind if there perhaps some special characters in your password that might give a problem.

**Comment by Captain-Chaos** [comment]
I tried several times, but I will try again taking special care to check for spaces. Would it be possible to have the app give an error message when there is a problem like that, so it's clearer what's going wrong? Or at least give some feedback that the button press was received?

**Comment by jtebbens** [comment]
It does give feedback or error connecting. But I can't cover the input errors. So not sure why it doesn't save.
Maybe when you tried to add and it fails. Stop pairing and go to settings of the HomeWizard app of Homey and hit diagnostic report for me.

**Comment by Captain-Chaos** [comment]
Well this is embarrassing. I tried again, and this time it worked. I tried several times, very carefully, on different devices. I have no idea what was different this time. Sorry to bother you and thanks for maintaining this!

**Comment by jtebbens** [comment]
No problem. Not uncommon to software or different devices and weird glitches.
