### ISSUE TITLE
Issue with setting the Homewizard preset in a flow

### ISSUE THREAD

**Issue by HarryV55** [jtebbens/com.homewizard#45]
Hello, I recently have switched from using Homewizard ro Homey. But still the Homewizard is present and I like to set the presets of Homewizard by Homey.
I can read a preset from Homewizard, only I have to specify 1, 2, 3 or 4 as a value, as I have to specify Thuis, Afwezig, Slapen of Vakantie. This seems to me not consistent.
Do I see this correct or do I something wrong in the programming of a flew.

**Comment by jtebbens** [comment]
There are HomeWizard preset cards in Homey for HomeWizard so no need to set or check with numbers. Also changing the preset goes properly with preset cards. So I can't relate your problem. I am using these preset cards myself for both the AND and THEN portions of the flows.

**Comment by HarryV55** [comment]
Thank you for your response. It made me realize that I did not add the and function correctly. Now it is working.
