### ISSUE TITLE
My HomeWizard Energy P1 can’t connect

### ISSUE THREAD

**Issue by mtvdham** [jtebbens/com.homewizard#46]
To day my connection of the HomeWizard P1 Energy dongle was gone. I have delete it but now I can’t install it again. Can some tel me how to install it. Now I see only “not found any device”.
I hope some can give me the right advice.

**Comment by jtebbens** [comment]
Could you elaborate if it had worked with Homey or only the HomeWizard Energy app? The dongle requires minimum firmware of 2.03 for the Homey HomeWizard app to work.

**Comment by mtvdham** [comment]
It haves works on the homey

**Comment by jtebbens** [comment]
Restart Homewizard app on Homey and try again.
I assume you are on the same wifi SSID?

**Comment by mtvdham** [comment]
Restart didn’t help

**Comment by jtebbens** [comment]
Which firmware does the dongle have?

**Comment by mtvdham** [comment]
Firmware 2.12
![Uploading 279D38A4-73F0-47B1-92A1-04D8130B7B42.jpeg…]()

**Comment by jtebbens** [comment]
Ok please try search for your dongle. When failing go to the settings section of the Homey Homewizard app and hit diagnostics. This will generate a report for me.

**Comment by mtvdham** [comment]
With mail adres?

**Comment by jtebbens** [comment]
Nope it has it internally so will receive it when generated.

**Comment by mtvdham** [comment]
50b9f3c5-d274-4e8d-a0c7-95621879cc82

**Comment by jtebbens** [comment]
failed, reason: connect EHOSTUNREACH 192.168.1.3:80',
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'


Your old homewizard unit has issues. But see nothing about dongle.

**Comment by mtvdham** [comment]
But I can’t install the dongle! 
![B2B6CF64-A9CC-4359-A34C-570EDE08C45D](https://user-images.githubusercontent.com/82967121/116032317-bdb82d00-a65f-11eb-8652-32bf174958b2.png)

**Comment by jtebbens** [comment]
Ok did you try to restart the dongle as well?
As it seems not sending mdns discover packets on your wifi network. Homey detects these and that is how we can install it.

**Comment by jtebbens** [comment]
Is your wifi dongle on a guest wifi? These block mdns packets.

**Comment by jtebbens** [comment]
No response after 2 weeks, will close issue and considered as resolved.
