### ISSUE TITLE
homey flow 'als' uitbreiden

### ISSUE THREAD

**Issue by timapeldoorn** [jtebbens/com.homewizard#47]
vandaag gelukkige gebruiker van uw App! ik gebruik homey, en miste bij 'als' de keuze om 1 van de 3 fase's te kiezen. Zo zou ik bijvoorbeeld een waarschuwing krijgen als een van de fase boven de 25amp (5900 watt)  verbruiken. Verder zeer handig!

**Comment by jtebbens** [comment]
Dat moet volgens mij al kunnen via "logica". 
Kies logica bij EN en vervolgens "tag" is groter dan.
Vervolgens tik je op de tag en daarna zoek je in de lijst de gewenste tag op.

**Comment by timapeldoorn** [comment]
krijg in de flow kaarten niet voor mekaar om waardes van stroom te splitsen in 3 waardes van de 3fase aansluiting. is het mgelijk
