### ISSUE TITLE
After deinstalling the P1 device it can't be installed again

### ISSUE THREAD

**Issue by pkoole** [jtebbens/com.homewizard#49]
Installed the P1 in homey. All OK. After 3 Day I got a red warning that the device wouldn't work anymore. I deinstalled the P1 device and wanted to install de P1 device again. I now keep getting the message Can't find a new device.
Tried everything. Deinstalling the app, update homey to 7.0.1. Restarted homey. Allways being Sûre the P1 adaptor was in discovery (bleu blinking) state.

**Comment by jtebbens** [comment]
Wifi dongle should be green upon adding to homey else it will not be discovered.
Don't mess up homewizard setup with homey setup.
The blue blink is to setup homewizard dongle first. It MUST be green when you want to add it to homey.

**Comment by pkoole** [comment]
Still the same result with a green Light. Still 'Er zijn geen nieuwe apparaten gevonden.'
A very short time some other te't was shown. Too short to read.

**Comment by jtebbens** [comment]
Which firmware does Homewizard energy dongle run?
You can find it in your Homewizard Energy app (not mine).
The mDNS support (discvery) is only available from 2.09 onwards.

**Comment by pkoole** [comment]
Version 2.12. But I the Local API setting was not checken. Change this setting to checked and the homey device is now discovarable again. Added the device. Running good. Thanks for the Quick support. Hope this info will help you to support other persons.

**Comment by jtebbens** [comment]
Thanks so they disabled it for WiFi dongle p1 as well by default which was not the case before. Ok will update read me and documentation.

**Comment by pkoole** [comment]
The setting was first enabled as I could instal the device the first time. I think I disabled the setting to see what happend, but later forgot about it. I suppose this is where the error message came from.

**Comment by jtebbens** [comment]
Ok fair enough. :)

**Comment by jtebbens** [comment]
Closing issue.
Problem was the Local API toggle in the Homewizard Energy was disabled upon discovery in Homey.
This toggle/switch enable/disables the mDNS protocol in the Wifi Dongle p1 which is mandatory for finding the dongle on the network.
