### ISSUE TITLE
HWE-P1 geeft geen actueel verbruik weer

### ISSUE THREAD

**Issue by dutchdavid81** [jtebbens/com.homewizard#50]
Alle totalen worden wel netjes weergegeven maar het actuele verbruik niet, niet het totale en ook niet per fase (ik heb er maar 1)

Ik heb een Landis + Gyr slimme meter met DSRM 4.0
De dongle draait op software versie 2.13
Homey pro draait op 7.1.3
De Homewizard app draait op versie 2.0.8

Via de Energy app van Homewizard zelf wordt het actuele verbruik wel netjes weergegeven 

![image](https://user-images.githubusercontent.com/90355609/132588938-8d324a5a-2a40-4f2c-a86a-16d86f68508f.jpeg)

![image](https://user-images.githubusercontent.com/90355609/132588953-eb04c4f3-15c8-4ff4-b754-408c9aed9ed9.jpeg)

Al verschillende malen alles opnieuw geïnstalleerd en gereset maar helaas zonder resultaat. Wat gaat hier mis?

**Comment by WNijhof** [comment]
Ik heb momenteel hetzelfde probleem, en mijn apparatuur heeft dezelfde versies.

**Comment by jtebbens** [comment]
Installeer versie v2.0.12 hopelijk gaat dat beter (staat nu in beta/test) app store.

**Comment by dutchdavid81** [comment]
@jtebbens 

Eerst test versie 2.0.12 geïnstalleerd over de bestaande app heen, dat hielp in eerste instantie niet. Vervolgens de app verwijderd (en daarmee ook de dongle) en vervolgens test versie 2.0.12 opnieuw geïnstalleerd en de P1 dongle opnieuw toegevoegd en nu werkt het wel.

Top! En bedankt voor de snelle (re)actie :-)

**Comment by WNijhof** [comment]
Dit heeft het opgelost inderdaad, snelle service!

**Comment by jtebbens** [comment]
Ok opgelost vanaf versie v2.0.12.
