### ISSUE TITLE
Toevoegen P1 meter aan Homey

### ISSUE THREAD

**Issue by Mechgtf** [jtebbens/com.homewizard#54]
Goedemiddag,

ook ik ervaar problemen met het toevoegen van de P1 meter aan Homey.
Als ik dit probeer zoals beschreven, krijg ik de melding "geen apparaat gevonden ".
Alles staat goed ingesteld, alles gecheckt en klopt.
Maar de P1 meter wordt niet gevonden.
Heb contact gelegd met Homey en krijg te horen dat het aan de community app zou liggen en niet bij hun en dat ik me hier zou moeten melden.
Dus bij deze.
Heb trouwens met de Homewizard Energy app geprobeerd en hier werkt deze wel.
Hoor graag de oplossing of dat ik nog meer gegevens moet aanleveren.

groet,

Marcel Simonis

**Comment by jtebbens** [comment]
Vervelend dat het niet werkt. Kan je meer vertellen over je netwerk? Gebruik je VLAN's in je WiFi? Welke versie firmware Homey? Welke versie Homewizard app? Staat local API in de device instellingen aan?

**Comment by Mechgtf** [comment]
Hallo, 
zover bekend geen VLAN.
Homey versie is 7.1.4
In de Homewizard app staat , deze app 3.11.9, Homewizard 3.403
domme vraag, waarom heb ik de homewizard app nodig als ik de P1 aan Homey wil toevoegen ???
zoals in Homey beschreven zou het gewoon plug and play moeten zijn.
local API ??? waar vind ik deze ??
gr.

**Comment by jtebbens** [comment]
Nu mag je weer proberen met discoveren / toevoegen. 
Dus ga naar je zone waar je de p1 wilt hebben druk op + en dan Homewizard en dan plaatje van de p1 dongle. Als het goed is moet deze dan gevonden gaan worden.

**Comment by Mechgtf** [comment]
Helaas, onze kennis is maar beperkt.
het enigste wat ik nog kan vertellen is dit, we kunnen de router bereiken en zien geen ip adres van de dongle.
dat is ook wat ik de hele tijd probeer te vertellen, als ik de P1 meter via Homey probeer te installeren, kan deze helemaal geen connectie maken omdat er wordt gezegd " geen apparaat gevonden ". dus hij gaat ook niet verder en er wordt ook geen ip adres gecreëerd.
heb nou weer hetzelfde gedaan via de energy app, deze vindt de dongle wel, vraagt om het wifi password en verbindt het apparaat. we zien dus ook bij de router nou een ip adres van de dongle naar voren komen.
dus ik zal het wel fout hebben, maar moeten we niet bij het begin beginnen ?? als de dongle in koppelmodus staat, waarom wordt deze dan niet gevonden ??

**Comment by Mechgtf** [comment]
Hallo, geloof het of niet, maar het is gelukt.
Deze beschrijving was me dus totaal onbekend, had ook niet gedacht dat het op deze manier zou moeten, ook bij Homey deze beschrijving niet gevonden. Als dit aan mij ligt, dan mijn excuses. Als dit nergens beschreven is, zou dit misschien wel handig zijn.
In ieder geval dank voor je hulp.
groet, Marcel.

**Comment by Mechgtf** [comment]
ik dacht vanmorgen dat het toch mis was, want sinds de aansluiting gisteren waren er wel gegevens, maar alles was bevroren en er veranderde niks. ik zag toen in de meterkast dat de dongle op rood stond, dus weer opnieuw verbonden en toen liep het wel.
inzake de tekst, ik ben nog op zoek naar de pagina, kom ik op terug, het staat wel ook niet goed bij Homey, maar dat zal ik hun melden.

**Comment by rjbaat** [comment]
Thnx voor je reactie! Ik heb de test app 2.1.3 geinstalleerd en opnieuw de p1 proberen toe te voegen. Ik krijg echter helaas dezelfde melding: Er zijn geen nieuwe aparaten gevonden. 

Kan het misschien zijn dat het device is blijven hangen in homey en niet is opgeschoond na het verwijderen van de oude homewizard energy app?

**Comment by jtebbens** [comment]
Kan je de socket even stroomloos maken en weer in stopcontact doen? Hopelijk brengt dit de
mdns weer op gang. Mocht dit werken dan moet je dit ook voor je P1 doen. Ik ben van handmatig ip afgestapt omdat de meeste mensen een DHCP range hebben en dus steeds veranderd. De
mdns lost dit vanzelf op (automatisch ip update als deze veranderd).

**Comment by rjbaat** [comment]
Ah kijk de p1 ziet hij en kan ik koppelen. Het lijkt of die de data goed oppikt. De energy socket kan ik ook koppelen. Alleen de data die deze doorgeeft is vreemd. Daar krijg ik vreemde data in het overzicht scherm. Alsof die een deel van de p1 meter pakt.

**Comment by jtebbens** [comment]
Geen idee. Wellicht socket even opnieuw koppelen.

**Comment by jtebbens** [comment]
Mooi. Dank maar blijft hobby en gepruts. :)

**Comment by Sander10361** [comment]
Goedemiddag,
ik ervaar het zelfde probleem. Mijn Homey Pro kan de P1 dongel niet vinden. Hij geeft aan ''er zijn geen nieuwe apparaten gevonden''. 

Ik zit op hetzelfde Wifi. Homey heeft versie 7.1.5 en de homewizard app  software 2.13. Heb je een idee wat ik kan doen? Ik heb de homey al herstart en de api url werkt ook en geeft data. http://192.168.x.x/api/v1/data

**Comment by jtebbens** [comment]
Local API staat aan?

Kind regards / groet,
Jeroen

**Comment by Sander10361** [comment]
hoi Jeroen, Ja de API staat aan.

**Comment by jtebbens** [comment]
Welke firmware heb je op de p1 dongle?
En staat multicast op je WiFi accesspoint aan?

Kind regards / groet,
Jeroen

**Comment by rjbaat** [comment]
Bij mij hielp het om de p1 te herstarten en daarna opnieuw proberen te koppelen.

**Comment by jtebbens** [comment]
Dat is inderdaad de laatste optie nog die ik kan geven.
Dongle is blijven hangen in zijn mdns broadcast. Herstart van de dongle start dit proces weer zodat Homey hem kan vinden en dat aan mijn app doorgeeft.

**Comment by Sander10361** [comment]
Ik heb de p1 verwijderd en opnieuw toegevoegd maar helaas zonder resultaat
Software dongel is 2.13.
Wat bedoel je precies met multicast op me wifi accespoint?

**Comment by jtebbens** [comment]
Instellingen van je WiFi router/accesspoint. Daar zit vaak ook een setting dat je iets met multicast verkeer kan doen.

Heb je ook al je dongle van het stroom gehaald dus uit/aan (adapter / stekker er uit zodat deze opnieuw opstart).

Verder tijdens toevoegen aan Homey moet je NIET op de dongle pair knop drukken. Je WiFi dongle moet groen blijven.

**Comment by Sander10361** [comment]
Bedankt voor je reactie! Het is gelukt :)

**Comment by jtebbens** [comment]
Wat was nu de oplossing?

**Comment by Sander10361** [comment]
Nou heel stom. Mijn Homey zat op een andere wifi dan dat ik dacht.. Ik was er heilig van overtuigd dat het op een andere wifi was aangesloten.
Toen ik daar achter kwam de p1 verwijderd en opnieuw geïnstalleerd en toen zag Homey hem wel

**Comment by jtebbens** [comment]
Ok, bedankt dus toch een andere wifi.

**Comment by pleumi** [comment]
Gebruikers met problemen hier, hebben jullie ook fritz.box (4060) ? Ik heb mijn P1 gekoppeld, en na aantal dagen error:request to http://192.168.188.20/api/v1/data failed, reason: connect EHOSTUNREACH 192.168.188.20:80
Via webinterface, ping en android app heb ik verbinding. P1 uit meter verwijderd en opnieuw aangesloten. Geen resultaat. Wel opnieuw aanmelden in andriod app geeft daarna verbinding. Suggestie dat het aan app ligt geloof ik niet want ook met http request met adv. flow geeft zelfde fout. 
Iemand een idee?

**Comment by jtebbens** [comment]
In je fritz box de P1 een vast ip geven?

**Comment by jtebbens** [comment]
https://nl.avm.de/service/knowledge-base/dok/FRITZ-Box-7581-int/201_Netwerkapparaat-altijd-hetzelfde-IP-adres-laten-toewijzen-door-FRITZ-Box/
