### ISSUE TITLE
Homewizard P1 meter toevoegen aan Homey

### ISSUE THREAD

**Issue by tschaak** [jtebbens/com.homewizard#58]
Goedendag,

Het lukt mij niet om de Homewizard P1 toe te voegen aan Homey.
Ik maak gebruik van de Homey app versie 6.10.0.842
versie HWE-P1 = 2.13
Ik heb de onderstaande methode gebruikt zoals vermeld op de website.

Hoe te verbinden met Homey:

- Kies 'apparaat toevoegen' in Homey's 'Apparaten' overzicht
- Zoek naar 'HomeWizard' en selecteer de 'Energy (P1 Dongle)'
- Volg de instructies zoals getoond door de koppel wizard

Zoeken op Homewizard geeft geen resultaten.

Enige idee wat een mogelijke kan zijn?

**Comment by jtebbens** [comment]
Ja ik gok dat je op de Energy P1 dongle PAIR knop drukt tijdens het toevoegen en daar moet je van afblijven.

**Comment by tschaak** [comment]
Nee, daar verander ik niks aan. Deze is aangesloten, brand groen en is via de Energy app uit te lezen.

**Comment by jtebbens** [comment]
Ok zitten ze beiden (Homey en Energy Dongle) op dezelfde AccessPoint SSID?

**Comment by jtebbens** [comment]
En welke versie van mijn Homewizard-app for Homey heb je geinstalleerd?

**Comment by tschaak** [comment]
Ja, gecontroleerd via Meters -> P1 meter geselecteerd en bij Meter instellingen staat het juiste Wi-Fi SSID
Lokale API staat ook aan.

**Comment by tschaak** [comment]
Nog even als extra info.
Ik maak gebruik van de Homey cloud oplossing.

**Comment by jtebbens** [comment]
Ah dan gaat het nooit werken. Homey Cloud ondersteund geen lokale wifi. Mijn Homewizard app is alleen geschikt voor de Homey Pro.

**Comment by tschaak** [comment]
ok, dat verklaart alles.
dankjewel voor de snelle reacties.

**Comment by jtebbens** [comment]
https://community.homey.app/t/homey-cloud-bridge-version-a-selection-of-available-apps-wiki/51520

![image](https://user-images.githubusercontent.com/18558267/146219871-66ddda91-dbb8-42d3-8d03-cf9e3b9c74d4.png)

**Comment by ThomasGeraedts** [comment]
Beste Jeroen,

Ik zit met hetzelfde probleem. Ik heb wel een Homey Pro maar krijf de P1 of Energy Sockets op geen mogelijkheid gekoppeld. Wat doe ik verkeerd? 

Alvast bedankt voor je reactie.

**Comment by jtebbens** [comment]
Staat je local api aan?

**Comment by ThomasGeraedts** [comment]
Goedemorgen Jeroen, Dank voor je antwoord. In HW staat die aan ja. Moet dat nog ergens anders ook aan staan? MvG Thomas

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: jtebbens ***@***.***>
Verzonden: Thursday, March 17, 2022 10:31:39 PM
Aan: jtebbens/com.homewizard ***@***.***>
CC: ThomasGeraedts ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [jtebbens/com.homewizard] Homewizard P1 meter toevoegen aan Homey (Issue #58)


Staat je local api aan?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjtebbens%2Fcom.homewizard%2Fissues%2F58%23issuecomment-1071518727&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NvvktxY0OPU7NfSpX%2FHB8L4w9GpidpebcdXX7QHDZOo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYI5KIJB3YMDPJMVJ2TUS3LVAOQDXANCNFSM5KD55SEQ&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BAPIX7IfvZ%2FmJm7KN3BFPheKcto7aaaiS6iYao9D31A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x1uc1VXWfM3B%2F%2FMFfeDx7dlAlgz1a%2BB9UH24tyxSklM%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N7TmH2XpzQOpUzJqmrGnC6Zxmqi8OBnRBIGApRadH%2FM%3D&reserved=0>.

**Comment by jtebbens** [comment]
Zitten homey en je p1 en sockets allemaal op zelfde wifi/accesspoint/ssid/netwerk?

Kind regards / Groet,
Jeroen

**Comment by ThomasGeraedts** [comment]
Hoi Jeroen,

Volgens mij wel, ik ga dat dit weekend nog een keer checken. Ik gebruik namelijk maar één netwerk voor mij apparaten. Ik kom hier op terug.
Nogmaals dank voor het snelle reageren, heel sympathiek.

MvG Thomas

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: jtebbens ***@***.***>
Verzonden: Friday, March 18, 2022 7:13:55 AM
Aan: jtebbens/com.homewizard ***@***.***>
CC: ThomasGeraedts ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [jtebbens/com.homewizard] Homewizard P1 meter toevoegen aan Homey (Issue #58)


Zitten homey en je p1 en sockets allemaal op zelfde wifi/accesspoint/ssid/netwerk?

Kind regards / Groet,
Jeroen

> Op 18 mrt. 2022 om 06:37 heeft ThomasGeraedts ***@***.***> het volgende geschreven:
>
> ﻿
> Goedemorgen Jeroen, Dank voor je antwoord. In HW staat die aan ja. Moet dat nog ergens anders ook aan staan? MvG Thomas
>
> Outlook voor iOS<https://aka.ms/o0ukef> downloaden
> ________________________________
> Van: jtebbens ***@***.***>
> Verzonden: Thursday, March 17, 2022 10:31:39 PM
> Aan: jtebbens/com.homewizard ***@***.***>
> CC: ThomasGeraedts ***@***.***>; Comment ***@***.***>
> Onderwerp: Re: [jtebbens/com.homewizard] Homewizard P1 meter toevoegen aan Homey (Issue #58)
>
>
> Staat je local api aan?
>
> —
> Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjtebbens%2Fcom.homewizard%2Fissues%2F58%23issuecomment-1071518727&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NvvktxY0OPU7NfSpX%2FHB8L4w9GpidpebcdXX7QHDZOo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYI5KIJB3YMDPJMVJ2TUS3LVAOQDXANCNFSM5KD55SEQ&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BAPIX7IfvZ%2FmJm7KN3BFPheKcto7aaaiS6iYao9D31A%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x1uc1VXWfM3B%2F%2FMFfeDx7dlAlgz1a%2BB9UH24tyxSklM%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8929708d13494afd09a808da085d8657%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831495017462283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N7TmH2XpzQOpUzJqmrGnC6Zxmqi8OBnRBIGApRadH%2FM%3D&reserved=0>.
> You are receiving this because you commented.Message ID: ***@***.***>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjtebbens%2Fcom.homewizard%2Fissues%2F58%23issuecomment-1072064628&data=04%7C01%7C%7C03656ffaf1e84973a05508da08a67c19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831808431339495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UeodNoyalr4AxrmJ%2F8ZvPUOpeHKHVxoLZbxs0SoWgW0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYI5KIPDYUZIKV3NCLUKBG3VAQNKHANCNFSM5KD55SEQ&data=04%7C01%7C%7C03656ffaf1e84973a05508da08a67c19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831808431339495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3QgqDHiKmeHAvQMNPbYWIbwwmNC62Z9KWE5G1eVUlPM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C03656ffaf1e84973a05508da08a67c19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831808431339495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZNiwq9wrkjnqVIdNjmGM30dQ%2F91cu7z8c1mlvO1APZ4%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C03656ffaf1e84973a05508da08a67c19%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637831808431339495%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oryGd20GHnFCOspR9l%2BFQ6O8EERuP7IzovTTP7rZYms%3D&reserved=0>.

**Comment by jtebbens** [comment]
Heb je je P1 al een keer gereset?  ( volledig stroomloos).

Toevoegen aan Homey blijf je can je p1 af. Kleur moet groen blijven .

Kind regards / groet,
Jeroen

**Comment by ThomasGeraedts** [comment]
Beste Jeroen,

Na het resetten van de Homey en de router is het gelukt om alle producten van Home Wizard te koppelen. Erg blij dat het gelukt is.
Maar nu krijg ik na een paar dagen deze melding. Kunt u mij uitleggen wat deze betekend?

Ik hoor graag van u.

Met vriendelijke groet,

Thomas Geraedts

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

**Comment by jtebbens** [comment]
Sorry ik zie geen plaatje

Kind regards / groet,
Jeroen

**Comment by jtebbens** [comment]
Dan heb je een multicast probleem in je (wifi) netwerk. Ik weet niet of je een iphone of een android toestel hebt maar zoek naar een app die mdns Browser (discovery) heet. https://apps.apple.com/us/app/discovery-dns-sd-browser/id305441017
Zoek dan naar _hwenergy._tcp in de zoek resulataten in die app. Dit zijn je Homewizard devices. Mocht je dit niet zien of vinden dan moet je je internet router een schop geven om het multicast verkeer op te starten. Kan ook zijn dat dit in je Wifi accesspoint geblockt wordt. Kijk dit in je instellingen na dat je multicast verkeer toestaat.

**Comment by jtebbens** [comment]
Ik zie niets dus weet niet wat je bedoeld.
