### ISSUE TITLE
Homewizard app weigert dienst

### ISSUE THREAD

**Issue by gersmit** [jtebbens/com.homewizard#59]
Geachte,

Na jaren gebruik te hebben gemaakt van de Homewizard app wil deze nu niet meer werken.
Verschillende malen verwijderd en gedownload an geinstalleerd maar geen succes.
App valt uit bij opstarten en accepteerd wachtwoord ook niet.

hoe kan ik dit oplossen?

Dank voor een reactie
Groet Ger

**Comment by jtebbens** [comment]
Beste Ger,

Vervelend om te horen dat het niet meer werkt.
Code van de app is bujna 3 maanden geleden voor het laatst geupdate dus mijn vraag zal eerder zijn wat er de lastste tijd bij U veranderd is?

Welke firmware homey?
Zitten homewizard en homey op zelfde wifi netwerk?
Kunt u een diagnose rapport van de Homewizard app sturen NA de foutmelding/crash?

**Comment by gersmit** [comment]
Hallo Jeroen,

Dank voor je snelle reactie.
Jarenlang perfect en dankbaar toestel en nu langzaam minder.
Dit viel mij op:
Vanmorgen geen wifi, dacht uitval Ziggo.
Dus opnieuw geinstalleerd maar gaat heel moeilijk., wifi wil heel moeilijk connecten.
Met pijn en moeite verbinding en zie dat er divere energy signalen en temp. meters verdwenen zijn, dus een crash?
Nu ga ik begrijpen dat de app problemen geeft.
Wat kan ik hieraan eventueel nog doen.

Wat kan ik, als dit niet meer gaat lukken met herstellen, voor apparaat gebruiken om dezelfde resultaat te bereiken.
Dan met name om de weermeters en energylink etc

Hoor nog graag even van jou hoe jij dit zou aanpakken.

Bij voorbaat dank en groet
Ger

**Comment by jtebbens** [comment]
Dat lijkt inderdaad dan op dat de Homewizard langzaam aan het overlijden is.
Wat je kan doen is paar keer de spanning er af halen van de Homewizard en kijken of dat helpt.
Je kan ook de adapter vervangen door een ander exemplaar en kijken of dat helpt.
Nog een andere mogelijkheid is je Homewizard tijdelijk een andere plek in je huis te geven (wifi verstoring uitsluiten).
Mocht het iets beter gaan dan kan je de verloren devices weer toevoegen/pairen aan je Homewizard en kijken of het iets tijdelijk was (crash). Of je probeert je geluk om nog een oude Homewizard op markt plaats te vinden voor weinig.

Stel je Homewizard is onbruikbaar geworden dan zit je wel met een probleem met Energylink en je Weerstation, deze werken vaak alleen maar met de Homewizard direct. Ik heb mijn Homewizard en Energylink nog wel maar inmiddels ook een Homewizard P1 wifi dongle met een splitter. Dus uitlezen van de slimme meter is dan opgelost. Homewizard verkoopt die dongle voor ongeveer 30 euro. Weerstation is helaas een ander verhaal. Daar heb ik geen ervaring mee en kan je hiermee niet helpen.

**Comment by jtebbens** [comment]
Het spijt mij maar het blijft een oud beestje. Kijk anders met een "ping" naar of alle netwerk pakketjes van je Windows 10 naar de Homewizard allemaal beantwoord worden. Als hier zaken wegvallen is dat de verklaring.
Maar dit is wel een signaal dat je actie moet gaan ondernemen dat Homewizard echt aan z'n einde komt.

**Comment by gersmit** [comment]
Helder Jeroen, dank.
Ik zal de HW voorzichtig vertellen dat ie met pensioen gaat.
Fijn dat je even heb meegedacht.

Groet Ger
