### ISSUE TITLE
New feature request: offset temperature

### ISSUE THREAD

**Issue by stevenv2201** [jtebbens/com.homewizard#60]
I'm integrating some 868 Mhz Smartwares temperature/humidity sensors via the Homewizard hardware and Homewizard app on my Homey. 
I noticed that the temperature of one of my sensors deviates with 1°C from the true temperature. Is there a possibility to add an "temperature_offset" functionality in future releases of the homewizard app? Similar to how you can indicate an offset for temperature measurements for temperature sensors added via the "draadloze weersensoren" app?

**Comment by jtebbens** [comment]
Not sure, have to see the code to understand the effort to add such request.

**Comment by stevenv2201** [comment]
I was able to implement this myself. I'm very new to github, don't know if you are able to see my suggested changes

**Comment by jtebbens** [comment]
Ok nice. Did you test/ run it against your own HomeWizard and Homey?

**Comment by stevenv2201** [comment]
Yes I did, see example below. Red = original homewizard app. Purple = with adjusted codes and an offset of -2°C
![image](https://user-images.githubusercontent.com/96480482/147221219-b2141822-1522-4d14-a7ac-189866b6a3f4.png)

**Comment by jtebbens** [comment]
I merged your code and testing it here locally with my Homewizard/Homey combo. Will push to beta when OK.

**Comment by jtebbens** [comment]
Ok its in the Homey app store now as test/beta.
I'll update the community forum/

https://homey.app/a/com.homewizard/test/

**Comment by stevenv2201** [comment]
OK, super! Thanks :-)
Steven Verhaeghe

**Comment by jtebbens** [comment]
Feature has been added as per 2.1.4 and above.
