### ISSUE TITLE
Hoelang blijft Homewizard nog bestaan

### ISSUE THREAD

**Issue by gersmit** [jtebbens/com.homewizard#63]
Hallo Jeroen,

Vorige keer gesproken over uitvallen HW.
Werkt nu redelijk alleen de tijd(zomer/wintertijd) loopt niet synchroon.
Eigelijk wil ik een andere HW aanschaffen, ik ben er namelijk erg tevreden over.
Maar voor ik dat doe wil graag weten hoelang de cloud omgeving van HW nog blijft bestaan.

Hoor graag waarvoor dank
Groet Ger

**Comment by jtebbens** [comment]
Hallo Ger,

Dan moet je niet bij mij zijn. Ik ben maar een thuis gebruiker/hobbyist die een Homewizard app gemaakt heeft voor Homey. Als je een vraag hebt over Homewizard zelf dan moet je contact opnemen met support desk van Homewizard zelf.
