### ISSUE TITLE
Not showing all power plugs

### ISSUE THREAD

**Issue by swanfield1979** [jtebbens/com.homewizard#65]
I tried installing it and I succeeded in adding the p1 module and one power plug. How ever I have 6. I don’t see my other power plugs and can’t add them

**Comment by jtebbens** [comment]
Did you enable all plugs their API flag?

Kind regards / groet,
Jeroen

**Comment by swanfield1979** [comment]
Well I can only select 1 plug so I don’t get the option to select the other api’s

**Comment by jtebbens** [comment]
Sorry don’t understand. In the official HomeWizard Energy app you must enable all local api settings per plug.

Kind regards / groet,
Jeroen

**Comment by swanfield1979** [comment]
Aha but I do understand now. I did not know I had to change the API and turn it on in the Energy app. So I did this and now they show :-) Thank you
