### ISSUE TITLE
Kan Base station niet toevoegen, kan niet op opslaan klikken

### ISSUE THREAD

**Issue by TimoRogier** [jtebbens/com.homewizard#67]
**Describe the bug**

** Version of Homey ** 7.2.1
** Version of the Homewizard Homey app ** 2.1.3
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jtebbens** [comment]
Per ongeluk een spatie voor je ip adres van base station?
Alleen ip adres invoeren. Anders een screenshot wat je invult bij toevoegen.

**Comment by TimoRogier** [comment]
huh..Ok na nu echt weet ik hoeveel achter elkaar geprobeerd pakt hij hem ineens! 
Maar dan niet via de app op een telefoon maar via een chromebook via de homey app...heel raar...opgelost hij is toegevoegd!
