### ISSUE TITLE
Homewizard energy do not show all devices

### ISSUE THREAD

**Issue by robsnoek** [jtebbens/com.homewizard#68]
**Describe the bug**

** Version of Homey **
** Version of the Homewizard Homey app **
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
I have in total 1 dongle, 3 energy sockets, and 4 kwh meters.
My homey pro has version 7.3.0
My Homewizard version is 2.1.3

In my Energy app i have set for all devices the local api to on.

Have downloaded and installed homewizard app.
installing the dongle i se various dongles, energy sockets and kwh meters.
find out what the real dongle is and install and working oke.
when i install al others i see that kwh meter is an energy socket and visa versa.

When I install Energy sockets i see Energy sockets
some energy sockets are oke but some are kwh meters.

When i install kwh meters is see i see kwh meters.
some are kwh meters some are energy sockets.

But over al i can install some devices right but some devices are still missing.

I hope you can help me to find the error.

BTW i had this issue last year also when there was only an energy app. That's is solved bij a new release.

Thanks Rob

**Comment by jaboh** [comment]
I have the same issue: only 4 out of 6 energy sockets are accessible from the Homey Pro. All 6 are fully accessible with the Homewizard Energy app.

**Comment by jtebbens** [comment]
@jaboh ok please power cycle the missing plugs (remove add).

**Comment by jaboh** [comment]
@jtebbens Thanks for the suggestion. Done that (several times), no effect.

**Comment by jtebbens** [comment]
Please double check those plugs are all 100% local api enabled and are on the SAME WiFi/subnet.

**Comment by jaboh** [comment]
@jtebbens Thanks for the hint. One of the sockets had API off, the other became visible after a Homey reboot.
