### ISSUE TITLE
Second P1 dongle not found.

### ISSUE THREAD

**Issue by Grumpy4711** [jtebbens/com.homewizard#69]
**Describe the bug**
The second P1 dongle in a other house is not found, only the first installed in the Energy app is found,

** Version of Homey **
7.3.0
** Version of the Homewizard Homey app **
2.1.3
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)
2.13
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery
Yes

**To Reproduce**
1. Add divice
2. Click on Energy P1 dongle
3. Install
4. No new device found message.

**Expected behavior**
find second P1 dongle

**Comment by jtebbens** [comment]
Is the other house on the same local LAN /wifi as your main house? Else it will never work.

**Comment by jtebbens** [comment]
Yes you need another Homey :)

Kind regards / Groet,
Jeroen
