### ISSUE TITLE
Geen actuele gegevens thermomenters

### ISSUE THREAD

**Issue by Plenty2run** [jtebbens/com.homewizard#70]
Beste Jeroen,
kan ik ergens instellen dat in de Homey app de actuele gegevens van Homewizard apparaten getoond worden? het lijkt er op dat deze alleen worden opgehaald op het moment dat ik de Homewizard opnieuw start. In de Homewizard app zelf heb ik wel gewoon actuele waarden.

![image](https://user-images.githubusercontent.com/101136310/157095035-1f0190b2-ea2b-4b90-a8f4-0de59743ee6f.png)

**Comment by jtebbens** [comment]
Die worden iedere 10 seconden ververst. Dus heb je eerder een WiFi connectie probleem denk ik.

**Comment by Plenty2run** [comment]
> Die worden iedere 10 seconden ververst. Dus heb je eerder een WiFi connectie probleem denk ik.

Bedankt voor je snelle reactie! Maar zowel de Homewizard als de Homey hebben een goede WIFI verbinding met de router, ik kan ze beide goed bereiken via internet. Dus ook de Homewizard app online. Of bedoel je wat anders? Is de Homey direct met de Homewizard verbonden of via de router? Wellicht is het probleem dan dat de 2 apparaten te dicht bij elkaar staan in ons vakantiehuis?

**Comment by jtebbens** [comment]
Homey en Homewizard moeten beide in zelfde lokale netwerk zitten.
Verder werkt mijn app niet via de cloud van Homewizard.

Kind regards / Groet,
Jeroen

**Comment by Plenty2run** [comment]
Ze zitten in hetzelfde netwerk. Misschien is dit het probleem, na verwijderen HW basisstation en opnieuw toevoegen raakt de app in de war?

![image](https://user-images.githubusercontent.com/101136310/157110176-fc3e1aef-41dd-4a0f-9af5-a4236f219fd2.png)

**Comment by jtebbens** [comment]
Wellicht nieuw ip adres gekregen intern? Maar idd verwijderen en opnieuw toevoegen is optie dan.

Kind regards / Groet,
Jeroen

**Comment by Plenty2run** [comment]
Nee, het IP adres blijft steeds gelijk. Maar verwijdert je app de oude IP-adressen niet? Ook nu ik de HW weer verwijderd heb en opnieuw toegevoegd heb ik er inmiddels een vijfde regel bij met hetzelfde IP-adres. Ik heb het gevoel dat bij verwijderen van het basisstation niet voldoende wordt opgeschoond en de app vervolgens naar de verkeerde verbinding kijkt bij actualiseren?

**Comment by jtebbens** [comment]
Ik volg je niet meer. De andere apparaten zijn gekoppeld aan je basis en krijgen een unieke code in homey. Dus basis verwijdern betekent dat de koppelde niet meer werken. Ik denk dat je alleen de basis steeds verwijderd en die anderen laat staan.

Verwijdere de extra’s, hou de basis en voeg opnieuw de extra units in homey dan zijn deze weer intern gekoppeld in homey met de basis.

Kind regards / Groet,
Jeroen

**Comment by Plenty2run** [comment]
Ik heb eerst alle HW apparaten verwijderd en dan pas het basisstation. Desondanks komt er na het opnieuw toevoegen van het basisstation weer een nieuwe IP regel bij. Ik weet niet welke ik moet kiezen. Bij allemaal kan ik daarna gewoon een HW apparaat kiezen. Nu heb ik ze allemaal eens aan de onderste gekoppeld en nu lijkt het er op dat in Homey wel de waarden geactualiseerd worden (maar niet elke 10 seconden, zitten 5-10 minuten tussen). Waarom blijven die andere IP regels hangen?

PS: overigens ontzettend fijn dat je deze app gemaakt hebt! Mocht Homewizard online een keer stoppen dan kan ik toch nog met de gekoppelde apparaten via Homey verder. Vandaar dat ik nu al vast even goed onderzoek of het allemaal werkt.

**Comment by jtebbens** [comment]
Hoi,

Sommige waarden veranderen alleen bij wijziging zoals een thermometer.
Mijn app vraagt iedere 10 seconden aan Homewizard alle waarden op, bij wijziging komt de nieuwe waarde en zal de timestamp van de bewuste waarde in homey geüpdate worden. Zolang homey en Homewizard hetzelfde laten zien is goed.

Welke “ip regels” bedoel je. Misschien screenshot?

Kind regards / Groet,
Jeroen

**Comment by Plenty2run** [comment]
Hoi Jeroen, zie screenshot eerder in dit draadje, daar waar je de HW moet kiezen bij toevoegen apparaten "Select HomeWizard". Daar staat nu inmiddels 5x 10.0.0.1

**Comment by jtebbens** [comment]
Dan heb je volgens mijn app nog meerdere basis stations gekoppeld. Zoniet dan apo herstarten wellicht dat dan die verdwijnen.

**Comment by jtebbens** [comment]
Ok fijn om te horen.
