### ISSUE TITLE
windmeter tijdelijk niet beschikbaar 

### ISSUE THREAD

**Issue by MartinvD1** [jtebbens/com.homewizard#71]
Goedemorgen, sinds de update zie ik een melding in Homey dat de windmeter tijdelijk niet beschikbaar is. Ik krijg nu geen gegevens meer binnen van de windmeter. Kan dat temaken hebben met de laatste Update?

**Comment by jtebbens** [comment]
Ja dat betekend dat je HomeWizard een slechte WiFi heeft en niet binnen 13 seconden informatie geeft. Dit was 20 seconden en heb ik naar 13 veranderd.

**Comment by hanshoevenaars** [comment]
Hallo Jeroen. Ik ondervindt hetzelfde probleem. Mijn wifi van wizard is altijd prima geweest. Kan je de setting aub weer terug zetten. Voor mij is het uitvallen van de windmeter een ramp. Mvg Hans

**Comment by jtebbens** [comment]
Probeer 2.1.9 die staat in test

**Comment by MartinvD1** [comment]
Versie 2.1.9 werkt bij mij. Tnx.

**Comment by jtebbens** [comment]
@hanshoevenaars probeer 2.1.9

**Comment by MartinvD1** [comment]
Goedemorgen, zojuist versie 2.1.10 ontvangen. Het probleem ervaar ik niet meer met de windmeter, maar wel met de regenmeter.

**Comment by jtebbens** [comment]
Vanaf versie 2.1.11 opgelost

**Comment by hanshoevenaars** [comment]
Heel hartelijk bedankt !!

 

Met vriendelijke groet,

 

Hans Hoevenaars

 

Van: jtebbens ***@***.*** 
Verzonden: donderdag 28 april 2022 16:35
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Mention
Onderwerp: Re: [jtebbens/com.homewizard] windmeter tijdelijk niet beschikbaar (Issue #71)

 

Vanaf versie 2.1.11 opgelost

**Comment by MartinvD1** [comment]
Tnx.
