### ISSUE TITLE
Windmeter een groot probleem 

### ISSUE THREAD

**Issue by hanshoevenaars** [jtebbens/com.homewizard#72]
Hallo Jeroen.
Sinds de update van de wizard app gisteren werkt de windmeter niet meer. Ik heb er veel flow aan hangen. Bijvoorbeeld ramen dicht, schermen omhoog bij wind. Wanneer kan de windmeter weer online. Of kan je tijdelijk terug naar een vorige versie?

Mvg Hans

**Comment by jtebbens** [comment]
Ik ga maandag kijken.

**Comment by hanshoevenaars** [comment]
> Hallo Jeroen. Sinds de update van de wizard app gisteren werkt de windmeter niet meer. Ik heb er veel flow aan hangen. Bijvoorbeeld ramen dicht, schermen omhoog bij wind. Wanneer kan de windmeter weer online. Of kan je tijdelijk terug naar een vorige versie?
> 
> Mvg Hans

Bij mij werkt de Beta versie ook.
Hartelijk dank

Mvg
Hans

**Comment by jtebbens** [comment]
Mooi, maar dat.betekend dat er structureel een connectie probleem blijft bij jullie Homewizards. Ik heb code moeten aanpassen voor de toekomst met firmware 7.4.0 en om geheugen en connectie problemen te voorkomen. Jullie zal steeds erger worden omdat de Homewizard traag blijft. Ik adviseer jullie om de Homewizard een andere plek te geven die een beter wifi verbinding heeft zonder andere wifi stoorzenders. Ik kan geen garantie geven dat dit goed blijft werken en de afhankelijkheid van Homewizard en de koppelingen met schermen etc is jullie eigen verantwoordelijkheid. Ik doe dit allemaal vrijwillig.

**Comment by hanshoevenaars** [comment]
Ik begrijp dat je dit vrijwillig doet, hartelijk dank daarvoor.

 

Om je een beeld te geven. Mijn Homewizard staat op 3 meter van mijn router. De homey (pro) ook.
Er zijn geen verbinding issues met de router (heb dat nagekeken signaal is optimaal). 
De windmeter en andere Wizard weer items ook ongeveer dezelfde afstand.

Ik begrijp niet helemaal waarom dit nu een probleem is geworden. Ik snap wel dat je up to date moet blijven met de Homey firmware.
Maar als dat betekend dat bijvoorbeeld de windmeter niet meer werkt dan heeft zo’n update niet veel zin.

Voor mij is dat zelfs erg vervelend omdat daar mijn ramen/zonneschermen op openen en sluiten. Jou App reageerd veel sneller dan bijvoorbeeld via een Netatmo App.

Met andere woorden je hebt een super App voor mijn Wizard gebruik. 

 

Ik hoop dat je de code zo kunt aanpassen dat eea netjes blijft werken.

 

Fijn weekend verder.

 

Met vriendelijke groet,

 

Hans Hoevenaars

Van: jtebbens ***@***.*** 
Verzonden: zondag 24 april 2022 11:18
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Author
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Mooi, maar dat.betekend dat er structureel een connectie probleem blijft bij jullie Homewizards. Ik heb code moeten aanpassen voor de toekomst met firmware 7.4.0 en om geheugen en connectie problemen te voorkomen. Jullie zal steeds erger worden omdat de Homewizard traag blijft. Ik adviseer jullie om de Homewizard een andere plek te geven die een beter wifi verbinding heeft zonder andere wifi stoorzenders. Ik kan geen garantie geven dat dit goed blijft werken en de afhankelijkheid van Homewizard en de koppelingen met schermen etc is jullie eigen verantwoordelijkheid. Ik doe dit allemaal vrijwillig.

**Comment by jtebbens** [comment]
Zet je auto update schuifje in de app uit. Dan blijf je bij deze test versie en krijg je geen updates meer die de boel kapot bij je maken.

**Comment by hanshoevenaars** [comment]
Heb ik al gedaan, laat je weten wanneer de laatste versie van je werkt?

 

Nogmaals dank.

 

Van: jtebbens ***@***.*** 
Verzonden: zondag 24 april 2022 12:15
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Author
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Zet je auto update schuifje in de app uit. Dan blijf je bij deze test versie en krijg je geen updates meer die de boel kapot bij je maken.

**Comment by jtebbens** [comment]
2.1.9 heb ik vrijdag al verzocht aan Athom naar stable te zetten maar is nog niet gebeurd. Maar ik geen uitzonderingen maken aangezien er nog ruim 3000 andere gebruikers zijn.

**Comment by hanshoevenaars** [comment]
Kan het zijn dat je de Energy link ook hebt aangepast?

Ik heb een hele rits apps die nu vreemd doen. Namelijk degene die reageren op zonlicht (opbrengst zonnecellen)

 

Groet,

 

Hans

 

Ps. Excuus dat ik je mail in weekend 

 

Van: jtebbens ***@***.*** 
Verzonden: zondag 24 april 2022 12:15
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Author
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Zet je auto update schuifje in de app uit. Dan blijf je bij deze test versie en krijg je geen updates meer die de boel kapot bij je maken.

**Comment by jtebbens** [comment]
Ik heb de homewizard timeouts aangepast en die doet windmeter, energylink, heatlink, regenmeter etc.

**Comment by hanshoevenaars** [comment]
Ik heb net even een filmpje gemaakt, dan kan je zien wat er gebeurd.  https://photos.app.goo.gl/BZqmR1czFa6BdRL66

 

Ergens rond de 38 sec in de film valt de app weg, en later nog eens etc.. Ik heb er een hoop timers aan hangen zodat mijn zonneschermen niet steeds in en uit gaan.

Als de energylink er mee stopt resetten al mijn timers die daar aan gelinked zijn, en dat gebeurd nu helaas dus heel vaak. Gevolg de flows werken niet naar behoren omdat de timer cycli niet kloppen. 

Heb je nog tijd om daar naar te kijken?

 

Alvast bedankt!

 

Vriendelijke groet,

Hans

 

 

Van: jtebbens ***@***.*** 
Verzonden: zondag 24 april 2022 13:05
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Author
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Ik heb de homewizard timeouts aangepast en die doet windmeter, energylink, heatlink, regenmeter etc.

**Comment by jtebbens** [comment]
Ik ben dit gedoe van slechte Homewizard wifi zat. Ik heb alles veranderd naar 20s polling en 18s timeout.
Test versie 2.1.10 staat in de test/beta store en succes ermee.

**Comment by jtebbens** [comment]
@hanshoevenaars bedankt voor je donatie

**Comment by hanshoevenaars** [comment]
Goedemorgen Jeroen, Ik snap dat je gefrustreerd raakt als na een update eea niet goed werkt bij gebruikers van je App. Ik ben je zeer dankbaar dat je dit doet. Ben zelf geen software maker ken ik alle ins en outs niet. Maar je App heeft altijd prachtig gewerkt en na de laatste (beta) nog steeds niet helaas (de energylink gaat er steeds uit). Ik ben zelf niet helemaal een digibeet maar als mijn wifi altijd goed heeft gewerkt met jou App en nu na de update niet niet meer. Hoe kan dan mijn wifi een oorzaak zijn? Ik vraag je dit omdat ik echt wil begrijpen hoe dit kan. Ik vind het zo jammer dat je App nu niet goed meer werkt. En hoop op een oplossing van jou zijde. Vriendelijke groet, Hans

**Comment by hanshoevenaars** [comment]
Donatie graag gedaan, koop graag nog een biertje voor je als het je lukt het probleem op te lossen.

**Comment by jtebbens** [comment]
Zou je ook je Homewizard main unit een keertje kunnen resetten, dus even stroom eraf voor paar seconden?

**Comment by hanshoevenaars** [comment]
Jeroen,

 

Ja dat had ik al gedaan. Ook gekeken of de wifi setting van de Homewizard nog goed is (2.4 Ghz). Dat kan met het laptop appje van Homewizard zelf (FWUpdate.exe). Dat is allemaal in orde. De setting is onveranderd. Homewizard werkt stabiel.

 

 

Van: jtebbens ***@***.*** 
Verzonden: maandag 25 april 2022 11:09
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Mention
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Zou je ook je Homewizard main unit een keertje kunnen resetten, dus even stroom eraf voor paar seconden?

**Comment by hanshoevenaars** [comment]
Hallo Jeroen,

 

Ik heb iets opvallends ontdekt.
Ik heb beide Apps (Homewizard en Homey Energyapp) naast elkaar laten lopen op mijn scherm.

Het blijkt dat na 3 cycli van 20 seconden jou app aangeeft device unavailable. Dat duurt een paar seconden en dan is de app terug. De counter staat dan ergens op 4 ofzo (filmpje 1)
Dit gebeurd telkens als er een waarde verandert in de Wizard app (van Homewizard).  

Daarom heb ik de S1 en S2 maar ook de slimme meter losgekoppeld van de Energymodule van Homewizard. De waardes zijn dus met alles 0 in die app.

Ook in jou app zijn de waardes 0 Kw etc. Je app update de waardes gewoon via de energylink echter de waardes blijven het zelfde 0Kw.
Nu lopen de cycli gewoon door en geeft jou app in Homey geen fout meer. (filmpje 2)



Zodra ik de S1 S2 en slimme meter weer aansluit op de Homewizard en jou app wisselende waardes moet verwerken gaat het weer mis.

 

Ik heb er2 twee filmpjes van gemaakt. Eentje met de energylink in vol bedrijf en eentje waarbij ik de sensors heb losgekoppeld op de energylink.  
Ik hoop dat je er wat aan hebt, en dat het je kan helpen (ons helpen) het probleem te takcelen.

 

Vriendelijke groet,

 

Hans

 

Filmpje 1 :  https://photos.app.goo.gl/uE7X5eXaRsEKewm78

 

Filmpje 2 : https://photos.app.goo.gl/o5r6g98KnRvKWuAA7

 

 

 

 

 

Van: jtebbens ***@***.*** 
Verzonden: maandag 25 april 2022 11:09
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Mention
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Zou je ook je Homewizard main unit een keertje kunnen resetten, dus even stroom eraf voor paar seconden?

**Comment by jtebbens** [comment]
Ik heb 2.1.11 in test staan, die werkt bij mij nu goed.

**Comment by jtebbens** [comment]
2.1.11 staat in test

**Comment by hanshoevenaars** [comment]
Hoi Jeroen,

 

Gefeliciteerd, het lijkt er op dat eea nu stabiel is.

De timers lopen rustig door zonder hickups.

 

Dank voor je inzet.

 

Fijne dag verder.

 

Met vriendelijke groet,

 

Hans

 

Van: jtebbens ***@***.*** 
Verzonden: maandag 25 april 2022 14:32
Aan: jtebbens/com.homewizard
CC: hanshoevenaars; Mention
Onderwerp: Re: [jtebbens/com.homewizard] Windmeter een groot probleem (Issue #72)

 

Ik heb 2.1.11 in test staan, die werkt bij mij nu goed.

**Comment by jtebbens** [comment]
Mooi dan zet ik hem naar stable
