### ISSUE TITLE
HomeWizard P1 meter

### ISSUE THREAD

**Issue by KoosH1951** [jtebbens/com.homewizard#73]
Jeroen,

I am running HomeWizard v2.1.16 for the P1 meter.
It is a great tool, however in my opinion it would make more sense to put the Gasmeter to the end.
You would then also see all the t1 and the t2 values on the same line.

So in that case you would see

Huidig resultaat    ---   Totaal verbruik kWh
Totaal t1 gebruik   ---  Totaal t1 teruglevering
Totaal t2 gebruik   ---  Totaal t2 teruglevering
Gasmeter 

Regards Koos Hendriks

**Comment by jtebbens** [comment]
That’s Homey default behavior as its alfabetic.

Kind regards / Groet,
Jeroen

**Comment by KoosH1951** [comment]
Strange then that "Totaal verbruik kWh" appears before "Totaal t1 gebruik".

Any idea what will happen when you enter a blank or a dot before Gasmeter?

**Comment by jtebbens** [comment]
No clue, haven’t tried. Am not aware if there a ways to control the order of the capabilities the device has and how these represent in Homey.

**Comment by KoosH1951** [comment]
Oke

**Comment by jtebbens** [comment]
https://community.homey.app/t/ability-to-choose-tiles-capbility/14544/45

**Comment by jtebbens** [comment]
Homey behavior out of my reach to resolve.
