### ISSUE TITLE
Heatlink homewizard niet meer in te stellen.

### ISSUE THREAD

**Issue by MartinvD1** [jtebbens/com.homewizard#74]
Goedemorgen, ik draai nu versie 2.1.27 van de homewizard app op Homey. Sinds de update naar 2.1.27 krijg ik de melding "homewizard.call is not a function" als ik via de Homey de thermostaat wil bijstellen. Doe ik iets fout?

**Comment by jtebbens** [comment]
Nee is fout in code. Ik kijk er na mijn vakantie naar.

**Comment by MartinvD1** [comment]
Oké, tnx. 👍🏻

**Comment by jtebbens** [comment]
2.1.28 in beta/test die zal moeten werken

**Comment by MartinvD1** [comment]
Ik heb net snel even getest. Ik kreeg geen foutmelding meer. Tnx.

**Comment by jtebbens** [comment]
Opgelost
