### ISSUE TITLE
Energy socket wifi netwerk gewijzigd

### ISSUE THREAD

**Issue by pvgent1** [jtebbens/com.homewizard#75]
Energy socket wifi netwerk gewijzigd ander ip-adres. Apparaat in Homey verwijderd, bij toevoegen apparaat krijg ik bij Energy socket geen nieuwe apparaten gevonden, local-api staan aan. Energy socket was toegevoegd in homey met ander ip-adres.
Energy socket is zichtbaar in energy app en ik kan de data via de api opvragen.

Is er iets van een caching?

**Comment by jtebbens** [comment]
Nee geen caching, energysocket word gevonden via mdns dus zoek het in je router. Bovendien als je in een ander netwerk als Homey zit dan heb je ook te maken met firewall regels die 80/tcp tegenhouden.

**Comment by pvgent1** [comment]
Ok, dan ga ik kijken naar mdns en mijn router.

**Comment by jtebbens** [comment]
Je kan niet zomaar je socket in een "gast" wifi netwerk doen. Vaak houdt de router dit tegen dat je vanaf je lokale wifi of LAN niet naar guest wifi mag.

**Comment by pvgent1** [comment]
Ik gebruik Unify, ik heb een trusted en een untrusted netwerk aangemaakt. De socket hangt nu is het untrusted netwerk en ik kan deze vanuit het trusted netwerk benaderen krijg data. In homey heb ik het oude apparaat verwijderd omdat deze verwees naar het oude ip-adres. De Homey zit op dit moment in het trusted netwerk. Ik kan de Homey ook in het untrusted netwerk hangen, op dit moment wordt er nog niets geblocked tussen beide (default unify)

**Comment by pvgent1** [comment]
Ga kijken wat er gebeurt als ik de socket in het oude netwerk hang, kijken of hij dan wel herkent wordt.

**Comment by jtebbens** [comment]
Heb je dan ook MDNS relay aanstaan in Unifi?
https://community.ui.com/questions/mDNS-What-does-it-do-and-should-I-use-it/df0bcae0-0f8f-4181-bd15-dfe6b921732b
https://community.ui.com/questions/Complete-Newbie-question-Enable-MDNS-w-out-a-Security-Gateway/c0c18d9a-745e-49e9-b883-83a7dcb68d98

Verder gebruik een MDNS browser op een iphone/tablet etc. Dan kan je zien of MDNS wel werkt van je untrusted naar trusted.

https://apps.apple.com/us/app/id305441017?mt=8&uo=4&at=1l3vnfE&ct=hsBonjour&pt=18645

**Comment by pvgent1** [comment]
Heb de energy socket terug gezet in het oude netwerk, het zelfde als Homey, ook nu wordt er geen nieuw apparaat gevonden. Heb de homey ook herstart en nu geven probleem is nu erger, homey kan nu ook de bestaande HomeWizard apparaten niet bereiken. Denk dat ik ergens verkeerd heb ingesteld, ga de router straks restarten.

**Comment by pvgent1** [comment]
Probleem 'gevonden' ben weer terug in de oude situatie energy socket kunnen toevoegen. Had Multicast en broadcast control aanstaan zonder hier exceptions in de lijst te hebben toegevoegd. VLAN Tutorials lijken soms zo eenvoudig echter zijn er blijkbaar een hoop instellingen die niet besproken worden. Dank voor de hulp, ik ga verder zoeken.

**Comment by pvgent1** [comment]
Heb het uiteindelijk werkend gekregen, moest wel de homewizard app herstarten om de Energy Sockets toe te voegen.
