### ISSUE TITLE
Knopen bij Windmeter ipv Km/uur

### ISSUE THREAD

**Issue by RuudKooijman** [jtebbens/com.homewizard#76]
**Describe the bug**
Wellicht geen bug maar meer een wens om de instelling van HomeWizard op de Windmeter over te nemen in Homey. 
In HomeWizard kun je de Windmeter op knp (knopen) instellen. In Homey kan alleen de km/m geselecteerd worden.

** Version of Homey 8.0.4 
** Version of the Homewizard Homey app v2.1.32
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09) (N/A)
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery (confirmed)

**Screenshots**

![HomeWizard knp](https://user-images.githubusercontent.com/25442376/187037671-ee0cc9ab-435e-49f9-928e-702509731abe.png)
![HomeWizard Instellingen Kts](https://user-images.githubusercontent.com/25442376/187037679-d461392f-4ef6-4e64-a156-a2061e3db61b.png)
![Homey HomeWizard Windmeter](https://user-images.githubusercontent.com/25442376/187037685-3a3802ca-e484-438d-a072-6c29bc4e9633.png)

**Comment by jtebbens** [comment]
Dit is vrij lastig omdat Homey zelf de km/u als standaard gebruikt.

**Comment by RuudKooijman** [comment]
Oke, dank je wel voor de feedback
Mvg
Ruud

Op za 27 aug. 2022 22:09 schreef jtebbens ***@***.***>:
