### ISSUE TITLE
[Req] Wifi signal in overzicht

### ISSUE THREAD

**Issue by Radiotechniman** [jtebbens/com.homewizard#77]
Een feature request; graag zou ik de wifi sterkte van mijn smartplugs zien in homey.  Sommige van mijn plugs geven af en toe een rood signaal wat betekend dat ze geen (wifi) connectie hebben, het zou fijn zijn omdat bij te kunnen houden. Als ik dan toch aan het vragen ben zou een ALS kaartje ook geweldig zijn; "Als signaal lager/hoger is dan XX" 

![image](https://user-images.githubusercontent.com/3715085/190087947-712f481d-7745-46ca-9fcd-e1b59388de84.png)
(screenshot van een shelly plug)

**Comment by jtebbens** [comment]
Wifi signaal toegevoegd maar nog geen “als” kaartje. Je kan ook met logica uitlezen.

**Comment by Radiotechniman** [comment]
Geweldig bedankt!
