### ISSUE TITLE
Can't add a device

### ISSUE THREAD

**Issue by Brons1981** [jtebbens/com.homewizard#78]
**Describe the bug**

Received error message device temporarily unavailable. Both on p1 dongle and 1 phase kWh meter.

WiFi connection is good and also accessible via the homewizard app.

restart homey resulted in red ring, had to restore with backup (backup used from when everything was still working). Still the same problem after recovery. Removed both devices, but can't add them anymore, get message "no new devices found"

** Version of Homey ** 

8.0.6

** Version of the Homewizard Homey app ** 

V2.1.33, during start problem experimental

** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)

 dongle p1 v2.13, kWh meter v2.11

** Confirm Local API has been enabled in Homewizard Energy app needed for discovery 

yes on both

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jtebbens** [comment]
Are p1 and kwh meter on same wifi as Homey or different subnet /network/wifi?

**Comment by Brons1981** [comment]
Yes same network 2.4 ghz and access point.Op 23 sep. 2022 om 20:57 heeft jtebbens ***@***.***> het volgende geschreven:﻿
Are p1 and kwh meter on same wifi as Homey or different subnet /network/wifi?

**Comment by jtebbens** [comment]
Alright, try to restart the Homey Homewizard app and discover again. If fail, then reboot homey. Main problem with searching is lack of mDNS (multicast dns). 
Maybe your accesspoint blocks multicast traffic so please check tgat as well.

**Comment by Brons1981** [comment]
Nice, changed some mDNS settings on Unifi and reboot homey and unifi solves the problem. I was afraid it was my six year old homey😅Thanks for the vey fast and good support. Have a nice weekend. Alex Op 23 sep. 2022 om 21:26 heeft jtebbens ***@***.***> het volgende geschreven:﻿
Alright, try to restart the Homey Homewizard app and discover again. If fail, then reboot homey. Main problem with searching is lack of mDNS (multicast dns).
Maybe your accesspoint blocks multicast traffic so please check tgat as well.

**Comment by jtebbens** [comment]
fixed
