### ISSUE TITLE
Tempature data check missing 

### ISSUE THREAD

**Issue by Raycokes2000** [jtebbens/com.homewizard#84]
**Describe the bug**
Temp sensors tend to loose connection with homewizard and no new data comes into homey. A re pair within homewizard appis the necessary. Is it possible to check incoming data once an hour or every 24 in a flow. 

Would be nice. 
Regards Raymond 

 
** Version of Homey **
Latest
** Version of the Homewizard Homey app*
latest
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)
NA
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery
Not applicable 
**To Reproduce**
Not, you can only see this no data available in hw app

**Expected behavior**
A check and message that data is not coming into homey from hw and is not received at least 
Once an hour
**Screenshots**

**Additional context**
![Screenshot_20230125_191347_nl homewizard android](https://user-images.githubusercontent.com/51300944/214649689-22c8cce3-6561-464d-bbfc-2522f8e84c38.jpg)

**Comment by jtebbens** [comment]
Sorry need more information, app version, setup, firmware, etc

**Comment by Raycokes2000** [comment]
Please check update of first message, is this now more clear?

**Comment by jtebbens** [comment]
If there is no update from your temperature to homewizard then nothing will change in Homey.

Your screenshot shows no data in two temperature in homewizard.
So those will not work in Homey.

**Comment by Raycokes2000** [comment]
Hello, that's why I like to see a tempature data check. But this is missing to select to use in flows. And I can repair these again

**Comment by jtebbens** [comment]
What you seek is already there. Create a flow, Check HOME, Then 'A device hasnt reported' and tick 24 hours. If the device hasnt updated for 24 hours you can create a trigger/alarm to your timeline or Phone.
