### ISSUE TITLE
P1 meter met fase 

### ISSUE THREAD

**Issue by Wouwmw** [jtebbens/com.homewizard#85]
Beste, ik heb een p1 meter van homewizard. En ook het plus abonnement. Hiermee zieniknde app ook de verschillende fases. Is het mogelijk om deze fase van levering en retour ook te zien in homey?.

**Comment by jtebbens** [comment]
Ik kan het alleen als het ook in de lokale api als info beschikbaar is.

http://x.x.x.x/api/v1/data

Vul het ipnadres in van je p1 en dan de output in ne browser.

**Comment by Wouwmw** [comment]
Dank je wel voor de info. Helaas staat deze fases er niet bij. Ik zal homewizard eens appen.

**Comment by jtebbens** [comment]
Ja daar zou ik wel iets mee kunnen.

**Comment by jtebbens** [comment]
Kan je jou output sturen dan heb ik data om mee te werken.

**Comment by Wouwmw** [comment]
{"smr_version":50,"meter_model":"Sagemcom T210-D ESMR5.0","wifi_ssid":"xxxxx","wifi_strength":82,"total_power_import_t1_kwh":11502.736,"total_power_import_t2_kwh":6565.789,"total_power_export_t1_kwh":3597.031,"total_power_export_t2_kwh":8176.792,"active_power_w":11396,"active_power_l1_w":3809,"active_power_l2_w":3811,"active_power_l3_w":3775,"total_gas_m3":null,"gas_timestamp":null}

**Comment by jtebbens** [comment]
Ok dank, ik ga er mee aan de slag.

**Comment by jtebbens** [comment]
Ik begrijp het even niet, Code voor 3 fase zit er al in maar jij ziet het niet in je p1?
Kan het zijn dat je onlangs van 1Fase naar 3Fase electra overgestapt bent in je meter kast?

**Comment by Wouwmw** [comment]
In de app zelf van homewizard van de p1 meter zie ik natuurlijk alles. Maar in homey gebruik ik ook de app homewizard versie 308. 
Sagemcom. 
Daar kan ik geen fase meters vinden. 
Het liefst zag ik daar ook verbruik per fase.

**Comment by jtebbens** [comment]
Je geeft geen antwoord op mijn vraag.....

**Comment by Wouwmw** [comment]
In de meterkast is het drie jaar 3 fase. De p1 meter heb ik later pas aangeschaft. 
De totale telling van het verbruik klopt wel.

**Comment by jtebbens** [comment]
Deze 3 meters moet je kunnen zien, anders moet je de P1 verwijderen en opnieuw aan Homey toevoegen.

active_power_l1_w":3809,"active_power_l2_w":3811,"active_power_l3_w":3775

**Comment by Wouwmw** [comment]
Ja ik heb de meters in beeld. Maar hoe kan ik nu het verbruik per dag per fase meten?
![image](https://user-images.githubusercontent.com/118289604/209714332-578b3ad4-d08c-4a3a-b3fa-fe90c659c7c3.png)

**Comment by jtebbens** [comment]
Daar heb je Power by the hour app voor nodig.
Mijn app geeft alleen de info van de p1 meter wat "nu" is. Voor dagelijkse totalen zal je die andere app er bij moeten installeren. En daar na een meter van die app toevoegen en daarna deze tijdens het toevoegen kiezen voor de p1 als bron.
