### ISSUE TITLE
total usage != usage t1 + usage t2

### ISSUE THREAD

**Issue by RobinBol** [jtebbens/com.homewizard#86]
**Describe the bug**

De totaal verbuik kWh waarde lijkt niet te kloppen, in de screenshots is de waarde 1100.93, maar dit is niet gelijk aan 673.05 + 611.92 of (673.05 + 611.92) - (184.05 + 465.22). Gek genoeg lijkt het gelijk aan (673.05 + 611.92) - 184.05.

** Version of Homey ** v8.1.0
** Version of the Homewizard Homey app ** v3.0.8
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09) 4.14
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery yes

**To Reproduce**
-

**Expected behavior**

**Screenshots**

![IMG_BC1BE961C49C-2](https://user-images.githubusercontent.com/5762579/211379124-00c1368a-08ae-441b-9c36-ecefb1eb97b3.jpeg)

![IMG_BC1BE961C49C-1](https://user-images.githubusercontent.com/5762579/211379109-8b6c26f4-484b-47fc-8684-e09d083e3d7f.jpeg)

**Additional context**

App log id `61598348-0f98-4067-b3d9-d31829bfcbc6`.

**Comment by jtebbens** [comment]
Klopt ik heb ook een andere gebruiker op forum met zelfde probleem. Nieuwe p1 Firmware heeft meer impact dan ik dacht. Ik los het morgen op.

**Comment by jtebbens** [comment]
Versie 3.1.0 staat in test met als het goed is een fix voor de Totaal verbruik KWH

**Comment by RobinBol** [comment]
Yes, fix werkt, bedankt! Moet zeggen dat de titel nog wel een beetje misleidend is, bij "totaal verbruik" had ik niet direct het idee dat het gebruik - productie was.

**Comment by jtebbens** [comment]
Ik sta open voor suggesties. Blijft sowieso lastig engels/nederlands en dan wat er met de verschillende energie dingen duidelijk te maken.
