### ISSUE TITLE
The accuracy of the Homey HWE-P1-G1 data is limited to 2 decimal places not 3 like te HomeWizard phone app or smartmeter

### ISSUE THREAD

**Issue by SiskoBen** [jtebbens/com.homewizard#87]
Hi, 
I noticed that the number of decimal places provided with the Homey HomeWizard app is only 2 decimal places after the decimal point while the actual HomeWizard app on the phone shows the actual full accuracy as it comes from the smartmeter.
This is for the HWE-P1-G1, the water meter HWE-WTR does seem to provide the full accuracy and shows 3 decimal places both in Homey and in the HomeWizard phone app. The JSON output by te local API of the device HWE-P1-G1 does provide the full accuracy

**Comment by jtebbens** [comment]
I am pulling the JSON output but its Homey that defaults it to 2 decimals.

**Comment by SiskoBen** [comment]
Hi @jtebbens,
OK, how does this work with the watermeter then? the WHE-WTR gives 3 decimals (in the JSON) and Homey does display 3 decimals as well through the HomwWizard Homey App. Note that before I had the HWE-P1-G1 I had a P1-cable connected to a Raspberry-Pi running Domoticz which was querried by the "Domoticz App" to put the Engergy (kwh) and Gas (m3) in Homey and this was displaying 3 decimals in Homey correctly.
Who should fix the issue that the HomeWizard app in Homey does not register or display the full 3 decimals?

**Comment by SiskoBen** [comment]
I see that the WaterMeter decimals was increased from 2 to 3 over a year ago https://github.com/athombv/node-homey-lib/pull/285#issuecomment-892711698
Strange that energy is not the same in the HomeWizard App even though the Domoticz App seems to be able to have an energy 'device' in Homey with 3 decimal accuracy

**Comment by jtebbens** [comment]
I do

**Comment by jtebbens** [comment]
Added in 3.1.4

**Comment by SiskoBen** [comment]
Hi @jtebbens,
I have now gotten v3.1.6 installed on my homey but only the Electricity meter has been updated to show 3 decimals but te gas meter does not (it still shows a maximum of 2 decimals, can you fix this as well in a future version?

**Comment by jtebbens** [comment]
Well the request was on power/energy and only those are reflected as custom values. The gasmeter is a standard Homey one. But sure I can add it but that needs more coding.
