### ISSUE TITLE
Gas readings of the Homey HWE-P1-G1 data is limited to 2 decimal places instead of 3 like the HomeWizard phone app or smartmeter

### ISSUE THREAD

**Issue by SiskoBen** [jtebbens/com.homewizard#88]
In the now closed ticket  [https://github.com/jtebbens/com.homewizard/issues/87](url) The issue was described that the Homey HomeWizard app is only exposing 2 decimal places from the available 3 decimal places of the HWE-P1-G1 device. The closed ticket was closed after the Electricity-Energy readings were changed from 2 decimal placed to 3 decimal places (like in the HWE-P1-G1 device and it's accompanying mobile phone app). However the Gas readings (from the same HWE-P1-G1 device) were not changed at that time. 
This ticket is therefor to request the Gas readings in the Homey HomeWizard app to be also the full resolution of that of the HWE-P1-G1 device (i.e., 3 decimal places instead of 3 decimal places).

**Comment by jtebbens** [comment]
Already implemented in 3.1.7
