### ISSUE TITLE
Homewizard availabel for homey bridge

### ISSUE THREAD

**Issue by edwinsabel** [jtebbens/com.homewizard#89]
Is there a possibility for the app to be used wit Homey bridge.

**Comment by jtebbens** [comment]
Can you explain your use case?
Problem with Homey Bridge atm is it doesnt support local wifi.

**Comment by edwinsabel** [comment]
I want to use the Homey bridge. In the specs it says only supported on Homey Pro

**Comment by jtebbens** [comment]
Correct, as the homey bridge has limitation to local wifi networking which is mandatory for Homewizard devices LOCAL API access. Sadly I can't change this as this a Homey/Athom choice and they removed local access to wifi devices.

**Comment by edwinsabel** [comment]
Thanks for the information. I will ask the same to Homey, perhaps they will change their policy
