### ISSUE TITLE
Meterstanden energylink

### ISSUE THREAD

**Issue by MartinvD1** [jtebbens/com.homewizard#91]
Sinds de laatste (test) update, update hij de meterstanden niet meer. Overige data wordt wel verzonden.

**Comment by jtebbens** [comment]
Vervelend, kan je een diagnose rapport sturen?

**Comment by jtebbens** [comment]
---- stdout ----
HomeWizard app ready!
HomeWizard Kakusensors has been inited
HomeWizard Wattcher has been inited
HomeWizard has been inited
HomeWizard Heatlink has been inited
HomeWizard EnergyLink has been inited
HomeWizard Thermometer has been inited
HomeWizard Windmeter has been inited
HomeWizard Rainmeter has been inited
add device: "HomeWizard"
HomeWizard Heatlink Heatlink has been inited
add device: "Heatlink"
HomeWizard Windmeter Windmeter has been inited
add device: "Windmeter"
HomeWizard Rainmeter Regenmeter  has been inited
add device: "Regenmeter "

---- stderr ----

**Comment by MartinvD1** [comment]
***@***.***

Hoj zou er toch moeten zijn. Hij update wel, maar alleen de meterstanden niet.

Met vriendelijke groet,

Martin

Van: jtebbens ***@***.***>
Verzonden: maandag 12 juni 2023 20:04
Aan: jtebbens/com.homewizard ***@***.***>
CC: MartinvD1 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jtebbens/com.homewizard] Meterstanden energylink (Issue #91)

Ik zie helemaal geen energylink. -Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: <="" div="">
DuckDuckGo removed 1 tracker.
More →

Ik zie helemaal geen energylink.

-

**Comment by jtebbens** [comment]
Ik ga kijken. Zal mijn energylink eens uit de doos halen. Denk dat nieuwe code van het uitlezen van Homewizard hoofdunit de boel overhoop gooit. Gebruik zelf de P1 dongle dus ik zie de hele energylink niet meer voorbij komen tijdens mijn testen van de nieuwe code.

**Comment by MartinvD1** [comment]
Tnx, ik wacht het af.

Met vriendelijke groet,

Martin

Van: jtebbens ***@***.***>
Verzonden: maandag 12 juni 2023 20:18
Aan: jtebbens/com.homewizard ***@***.***>
CC: MartinvD1 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jtebbens/com.homewizard] Meterstanden energylink (Issue #91)

Ik ga kijken. Zal mijn energylink eens uit de doos halen. Denk dat nieuwe code van het uitlezen van Homewizard hoofdunit de boel overhoop gooit. Gebruik zelf de P1 dongle dus ik zie de hele energylink
DuckDuckGo removed 1 tracker.
More →

Ik ga kijken. Zal mijn energylink eens uit de doos halen. Denk dat nieuwe code van het uitlezen van Homewizard hoofdunit de boel overhoop gooit. Gebruik zelf de P1 dongle dus ik zie de hele energylink niet meer voorbij komen tijdens mijn testen van de nieuwe code.

-

**Comment by jtebbens** [comment]
Ik heb net test versie v3.2.4 geupload. Kijk of dit beter gaat.

**Comment by MartinvD1** [comment]
Yes, hij doet het weer. Tnx 😀

Met vriendelijke groet,

Martin
________________________________

**Comment by jtebbens** [comment]
Fijn! Bedankt voor de bevestiging.
