### ISSUE TITLE
Homey lost connection

### ISSUE THREAD

**Issue by bonm014** [jtebbens/com.homewizard#94]
**Describe the bug**
I am using homewizard from my homey for an year or so.
But since this week all the electrics (socket, p1, water, fase 3) are no longer found within homey.
The Android homewizard app does, they are connected to wifi.
Local api is enabled, I even disabled and enabled it again to make sure.
Restarted homey and app. Powered off the electrics and start up again.
When I removed the device from homey I can't add them again

** Version of Homey **
10.0.5
** Version of the Homewizard Homey app **
3.2.25
** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)
4.19
** Confirm Local API has been enabled in Homewizard Energy app needed for discovery
CONFIRM

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2024-01-11-20-05-40-94_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/jtebbens/com.homewizard/assets/7635241/54d6bab1-7002-4ad9-8542-617872bb6e00)

**Additional context**
Diagnostics report
1466054e-f11b-47b0-ac3a-9747b8792eb0

**Comment by jtebbens** [comment]
Sounds like a mDNS problem to me in your wifi network.
Can you see your devices in a mDNS discovery/browser app as per first forum topic?

**Comment by bonm014** [comment]
I could see everything, but I rebooted my wifi and all came back again
