### ISSUE TITLE
S1 not updated since last update

### ISSUE THREAD

**Issue by seekelen** [jtebbens/com.homewizard#98]
**Describe the bug**

S1 not updated since last update

** Version of Homey **
10.0.9
** Version of the Homewizard Homey app **
3.3.10

** Version of the firmware of the device you are trying to add (Homewizard wifi dongle p1 must be 2.09)

** Confirm Local API has been enabled in Homewizard Energy app needed for discovery

**To Reproduce**
1. See screenshot 

**Expected behavior**
The current numbers in my HomeWizard (old one) in S1

**Screenshots**

**Additional context**
all devices has
![IMG_0865](https://github.com/jtebbens/com.homewizard/assets/6258665/321211d2-fb34-44d1-a7f6-7b123ace8040)
 been restarted

**Comment by jtebbens** [comment]
Isn't there a new S1 there?
Check the labels in that view.
Am currently on holiday so don't have access to the code.

**Comment by seekelen** [comment]
Thanks for the tip. The S1 had turned around with S2.
